const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  isPackaged: process.argv.includes('--scribe-packaged'),
  launchedWithFile: process.argv.includes('--scribe-launch-file'),
  pathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return ''; } },
  getFolderPath: (name) => ipcRenderer.invoke('folder-path', name),
  revealFolder: (name) => ipcRenderer.send('reveal-folder', name),
  onLoadFile: (callback) => ipcRenderer.on('load-file', (_event, data) => callback(data)),
  onNavigate: (callback) => ipcRenderer.on('viewer-navigate', (_event, data) => callback(data)),
  onHighlight: (callback) => ipcRenderer.on('viewer-highlight', (_event, data) => callback(data)),
  onMenuAction: (callback) => ipcRenderer.on('menu-action', (_event, id) => callback(id)),
  sendMenuState: (state) => ipcRenderer.send('menu-state', state),
  getPowerState: () => ipcRenderer.invoke('power-state'),
  onPowerChanged: (callback) => ipcRenderer.on('power-changed', (_event, data) => callback(data)),
  minimize: () => ipcRenderer.send('window-minimize'),
  toggleMaximize: () => ipcRenderer.send('window-maximize-toggle'),
  toggleFullScreen: () => ipcRenderer.send('window-fullscreen-toggle'),
  onMaximizedChange: (callback) => ipcRenderer.on('window-maximized', (_event, on) => callback(on)),
  onFullScreenChange: (callback) => ipcRenderer.on('window-fullscreen', (_event, on) => callback(on)),
  onRecentFiles: (callback) => ipcRenderer.on('recent-files', (_event, files) => callback(files)),
  openRecent: (index) => ipcRenderer.send('open-recent', index),
  clearRecent: () => ipcRenderer.send('clear-recent'),
  onAppTeardown: (callback) => ipcRenderer.on('app-teardown', () => callback()),
  appTeardownDone: () => ipcRenderer.send('app-teardown-done'),
});
