async function TesseractCore(moduleArg={}){var moduleRtn;var e=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type;if(ca){const {createRequire:a}=await import(/* webpackIgnore: true */ "module");var require=a(import.meta.url)}var da="./this.program",ea=(a,b)=>{throw b;},fa=import.meta.url,ha="",ia,ja;
if(ca){var fs=require("fs");fa.startsWith("file:")&&(ha=require("path").dirname(require("url").fileURLToPath(fa))+"/");ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ha=(new URL(".",fa)).href}catch{}ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";
b.send(null);return new Uint8Array(b.response)});ia=async a=>{if(ka(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var la=console.log.bind(console),ma=console.error.bind(console),na,oa=!1,ka=a=>a.startsWith("file://"),pa,qa,ra,g,l,sa,n,p,ta,ua,va,wa=!1;function xa(){var a=ra.buffer;g=new Int8Array(a);sa=new Int16Array(a);l=new Uint8Array(a);new Uint16Array(a);n=new Int32Array(a);p=new Uint32Array(a);ta=new Float32Array(a);ua=new Float64Array(a);va=new BigInt64Array(a);new BigUint64Array(a)}
function r(a){e.onAbort?.(a);a="Aborted("+a+")";ma(a);oa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");qa?.(a);throw a;}var ya;async function za(a){if(!na)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ya&&na)a=new Uint8Array(na);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Aa(a,b){try{var c=await za(a);return await WebAssembly.instantiate(c,b)}catch(d){ma(`failed to asynchronously prepare wasm: ${d}`),r(d)}}async function Ba(a){var b=ya;if(!na&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){ma(`wasm streaming compile failed: ${d}`),ma("falling back to ArrayBuffer instantiation")}return Aa(b,a)}
class Ca{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Da=a=>{for(;0<a.length;)a.shift()(e)},Ea=[],Fa=[],Ga=()=>{var a=e.preRun.shift();Fa.push(a)};
function Ha(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return g[a];case "i8":return g[a];case "i16":return sa[a>>1];case "i32":return n[a>>2];case "i64":return va[a>>3];case "float":return ta[a>>2];case "double":return ua[a>>3];case "*":return p[a>>2];default:r(`invalid type for getValue: ${b}`)}}var Ia=!0;
function Ja(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":g[a]=b;break;case "i8":g[a]=b;break;case "i16":sa[a>>1]=b;break;case "i32":n[a>>2]=b;break;case "i64":va[a>>3]=BigInt(b);break;case "float":ta[a>>2]=b;break;case "double":ua[a>>3]=b;break;case "*":p[a>>2]=b;break;default:r(`invalid type for setValue: ${c}`)}}
var Ka="undefined"!=typeof TextDecoder?new TextDecoder:void 0,v=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},
w=a=>a?v(l,a):"";class La{constructor(a){this.Cf=a-24}gg(a,b){p[this.Cf+16>>2]=0;p[this.Cf+4>>2]=a;p[this.Cf+8>>2]=b}}
var Ma=0,Pa=0,Ra=()=>{var a=n[+Qa>>2];Qa+=4;return a},Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Va=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Wa=(a,b)=>Ta(a+"/"+b),Xa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Za=a=>{(Za=Xa())(a)},$a=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:x.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sa(b.split("/").filter(f=>!!f),!c).join("/");return(c?"/":"")+b||"."},ab=
(a,b)=>{function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var t=k.length-1;0<=t&&""===k[t];t--);return m>t?[]:k.slice(m,t-m+1)}a=$a(a).slice(1);b=$a(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,h=0;h<d;h++)if(a[h]!==b[h]){f=h;break}d=[];for(h=f;h<a.length;h++)d.push("..");d=d.concat(b.slice(f));return d.join("/")},bb=[],cb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
db=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.codePointAt(h);if(127>=k){if(c>=d)break;b[c++]=k}else if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6;b[c++]=128|k&63}else if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12;b[c++]=128|k>>6&63;b[c++]=128|k&63}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63;b[c++]=128|k>>6&63;b[c++]=128|k&63;h++}}b[c]=0;return c-f},eb=(a,b)=>{var c=Array(cb(a)+1);a=db(a,c,0,c.length);b&&(c.length=a);return c},fb=[];
function gb(a,b){fb[a]={input:[],output:[],Wf:b};hb(a,ib)}
var ib={open(a){var b=fb[a.node.rdev];if(!b)throw new x.Df(43);a.tty=b;a.seekable=!1},close(a){a.tty.Wf.fsync(a.tty)},fsync(a){a.tty.Wf.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Wf.Eg)throw new x.Df(60);for(var f=0,h=0;h<d;h++){try{var k=a.tty.Wf.Eg(a.tty)}catch(m){throw new x.Df(29);}if(void 0===k&&0===f)throw new x.Df(6);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.atime=Date.now());return f},write(a,b,c,d){if(!a.tty||!a.tty.Wf.vg)throw new x.Df(60);try{for(var f=0;f<d;f++)a.tty.Wf.vg(a.tty,
b[c+f])}catch(h){throw new x.Df(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return f}},jb={Eg(){a:{if(!bb.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(f){if(f.toString().includes("EOF"))c=0;else throw f;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}bb=eb(a,!0)}a=bb.shift()}return a},vg(a,b){null===b||10===
b?(la(v(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(la(v(a.output)),a.output=[])},oh(){return{Bh:25856,Dh:5,Ah:191,Ch:35387,zh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ph(){return 0},qh(){return[24,80]}},kb={vg(a,b){null===b||10===b?(ma(v(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(v(a.output)),a.output=[])}},mb=a=>{a=65536*Math.ceil(a/65536);var b=lb(65536,a);b&&l.fill(0,b,b+a);return b},
y={Sf:null,Jf(){return y.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||x.isFIFO(c))throw new x.Df(63);y.Sf||(y.Sf={dir:{node:{Of:y.Ef.Of,Qf:y.Ef.Qf,lookup:y.Ef.lookup,Vf:y.Ef.Vf,rename:y.Ef.rename,unlink:y.Ef.unlink,rmdir:y.Ef.rmdir,readdir:y.Ef.readdir,symlink:y.Ef.symlink},stream:{Mf:y.Ff.Mf}},file:{node:{Of:y.Ef.Of,Qf:y.Ef.Qf},stream:{Mf:y.Ff.Mf,read:y.Ff.read,write:y.Ff.write,ag:y.Ff.ag,dg:y.Ff.dg}},link:{node:{Of:y.Ef.Of,Qf:y.Ef.Qf,readlink:y.Ef.readlink},stream:{}},
Ag:{node:{Of:y.Ef.Of,Qf:y.Ef.Qf},stream:x.Og}});c=x.createNode(a,b,c,d);z(c.mode)?(c.Ef=y.Sf.dir.node,c.Ff=y.Sf.dir.stream,c.Gf={}):x.isFile(c.mode)?(c.Ef=y.Sf.file.node,c.Ff=y.Sf.file.stream,c.Lf=0,c.Gf=null):40960===(c.mode&61440)?(c.Ef=y.Sf.link.node,c.Ff=y.Sf.link.stream):8192===(c.mode&61440)&&(c.Ef=y.Sf.Ag.node,c.Ff=y.Sf.Ag.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Gf[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Mh(a){return a.Gf?a.Gf.subarray?a.Gf.subarray(0,a.Lf):new Uint8Array(a.Gf):
new Uint8Array(0)},Ef:{Of(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;z(a.mode)?b.size=4096:x.isFile(a.mode)?b.size=a.Lf:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Qf(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Lf!=b&&(0==b?
(a.Gf=null,a.Lf=0):(c=a.Gf,a.Gf=new Uint8Array(b),c&&a.Gf.set(c.subarray(0,Math.min(b,a.Lf))),a.Lf=b)))},lookup(){y.kg||(y.kg=new x.Df(44),y.kg.stack="<generic error, no stack>");throw y.kg;},Vf(a,b,c,d){return y.createNode(a,b,c,d)},rename(a,b,c){try{var d=nb(b,c)}catch(h){}if(d){if(z(a.mode))for(var f in d.Gf)throw new x.Df(55);ob(d)}delete a.parent.Gf[a.name];b.Gf[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Gf[b];a.ctime=a.mtime=Date.now()},rmdir(a,
b){var c=nb(a,b),d;for(d in c.Gf)throw new x.Df(55);delete a.Gf[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Gf)]},symlink(a,b,c){a=y.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new x.Df(28);return a.link}},Ff:{read(a,b,c,d,f){var h=a.node.Gf;if(f>=a.node.Lf)return 0;a=Math.min(a.node.Lf-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write(a,b,c,d,f,h){b.buffer===g.buffer&&(h=
!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Gf||a.Gf.subarray)){if(h)return a.Gf=b.subarray(c,c+d),a.Lf=d;if(0===a.Lf&&0===f)return a.Gf=b.slice(c,c+d),a.Lf=d;if(f+d<=a.Lf)return a.Gf.set(b.subarray(c,c+d),f),d}h=f+d;var k=a.Gf?a.Gf.length:0;k>=h||(h=Math.max(h,k*(1048576>k?2:1.125)>>>0),0!=k&&(h=Math.max(h,256)),k=a.Gf,a.Gf=new Uint8Array(h),0<a.Lf&&a.Gf.set(k.subarray(0,a.Lf),0));if(a.Gf.subarray&&b.subarray)a.Gf.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.Gf[f+
h]=b[c+h];a.Lf=Math.max(a.Lf,f+d);return d},Mf(a,b,c){1===c?b+=a.position:2===c&&x.isFile(a.node.mode)&&(b+=a.node.Lf);if(0>b)throw new x.Df(28);return b},ag(a,b,c,d,f){if(!x.isFile(a.node.mode))throw new x.Df(43);a=a.node.Gf;if(f&2||!a||a.buffer!==g.buffer){d=!0;f=mb(b);if(!f)throw new x.Df(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);g.set(a,f)}}else d=!1,f=a.byteOffset;return{Cf:f,zg:d}},dg(a,b,c,d){y.Ff.write(a,b,0,d,c,!1);return 0}}},pb=
(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},qb=async a=>{a=await ia(a);return new Uint8Array(a)},rb=0,sb=null,tb=()=>{rb--;e.monitorRunDependencies?.(rb);if(0==rb&&sb){var a=sb;sb=null;a()}},ub=()=>{rb++;e.monitorRunDependencies?.(rb)},vb=[],wb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.gg();for(var c of vb)if(c.canHandle(b))return c.handle(a,b);return a},yb=async(a,b,c,d,f,h,k,m)=>{var t=b?$a(Ta(a+"/"+b)):a,u=`cp ${t}`;ub(u);try{var C=c;"string"==typeof c&&(C=await qb(c));C=await wb(C,
t);m?.();h||xb(a,b,C,d,f,k)}finally{tb(u)}};function hb(a,b){x.Cg[a]={Ff:b}}function z(a){return 16384===(a&61440)}function nb(a,b){var c=z(a.mode)?(c=zb(a,"x"))?c:a.Ef.lookup?0:2:54;if(c)throw new x.Df(c);for(c=x.Rf[Ab(a.id,b)];c;c=c.bg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return x.lookup(a,b)}function ob(a){var b=Ab(a.parent.id,a.name);if(x.Rf[b]===a)x.Rf[b]=a.bg;else for(b=x.Rf[b];b;){if(b.bg===a){b.bg=a.bg;break}b=b.bg}}
function xb(a,b,c,d,f,h){var k=b;a&&(a="string"==typeof a?a:Bb(a),k=b?Ta(a+"/"+b):a);a=pb(d,f);k=x.create(k,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(f=c.length;d<f;++d)b[d]=c.charCodeAt(d);c=b}x.chmod(k,a|146);b=x.open(k,577);x.write(b,c,0,c.length,0,h);x.close(b);x.chmod(k,a)}}
function A(a,b={}){if(!a)throw new x.Df(44);b.fg??(b.fg=!0);"/"===a.charAt(0)||(a=x.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=x.root,f="/",h=0;h<a.length;h++){var k=h===a.length-1;if(k&&b.parent)break;if("."!==a[h])if(".."===a[h])if(f=Ua(f),x.sg(d)){a=f+"/"+a.slice(h+1).join("/");c--;continue a}else d=d.parent;else{f=Ta(f+"/"+a[h]);try{d=nb(d,a[h])}catch(m){if(44===m?.Kf&&k&&b.th)return{path:f};throw m;}!d.Pf||k&&!b.fg||(d=d.Pf.root);if(40960===(d.mode&61440)&&
(!k||b.Nf)){if(!d.Ef.readlink)throw new x.Df(52);d=d.Ef.readlink(d);"/"===d.charAt(0)||(d=Ua(f)+"/"+d);a=d+"/"+a.slice(h+1).join("/");continue a}}}return{path:f,node:d}}throw new x.Df(32);}function Bb(a){for(var b;;){if(x.sg(a))return a=a.Jf.Gg,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%x.Rf.length}function Cb(a){var b=Ab(a.parent.id,a.name);a.bg=x.Rf[b];x.Rf[b]=a}
function Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function zb(a,b){if(x.Fg)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Eb(a,b){if(!z(a.mode))return 54;try{return nb(a,b),20}catch(c){}return zb(a,"wx")}
function Fb(a,b,c){try{var d=nb(a,b)}catch(f){return f.Kf}if(a=zb(a,"wx"))return a;if(c){if(!z(d.mode))return 54;if(x.sg(d)||Bb(d)===x.cwd())return 10}else if(z(d.mode))return 31;return 0}function Gb(a,b){if(!a)throw new x.Df(b);return a}function B(a){a=x.Sg(a);if(!a)throw new x.Df(8);return a}function Hb(a,b=-1){a=Object.assign(new x.Lg,a);if(-1==b)a:{for(b=0;b<=x.Ng;b++)if(!x.streams[b])break a;throw new x.Df(33);}a.fd=b;return x.streams[b]=a}
function Ib(a,b=-1){a=Hb(a,b);a.Ff?.Gh?.(a);return a}function Jb(a,b,c){var d=a?.Ff.Qf;a=d?a:b;d??=b.Ef.Qf;Gb(d,63);d(a,c)}function Kb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.eg)}return b}function Lb(a){var b={yh:4096,Jh:4096,blocks:1E6,xh:5E5,wh:5E5,files:x.ug,Hh:x.ug-1,Kh:42,flags:2,Ph:255};a.Ef.Ig&&Object.assign(b,a.Ef.Ig(a.Jf.uh.root));return b}function Mb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return x.Vf(a,b|8192,c)}
function Nb(a,b,c,d){Jb(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Dg:d})}function Ob(a,b,c){if(z(b.mode))throw new x.Df(31);if(!x.isFile(b.mode))throw new x.Df(28);var d=zb(b,"w");if(d)throw new x.Df(d);Jb(a,b,{size:c,timestamp:Date.now()})}function Pb(a,b){a="string"==typeof a?a:Bb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ta(a+"/"+c);try{x.mkdir(d)}catch(f){if(20!=f.Kf)throw f;}a=d}}return d}
function Qb(a,b,c,d){a="string"==typeof a?a:Bb(a);b=Ta(a+"/"+b);return x.create(b,pb(c,d))}function Rb(a){if(!(a.rh||a.sh||a.link||a.Gf))if("undefined"!=typeof XMLHttpRequest)r("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Gf=ja(a.url)}catch(b){throw new x.Df(29);}}
function Sb(a,b,c,d,f){function h(q,K,X,Y,W){q=q.node.Gf;if(W>=q.length)return 0;Y=Math.min(q.length-W,Y);if(q.slice)for(var U=0;U<Y;U++)K[X+U]=q[W+U];else for(U=0;U<Y;U++)K[X+U]=q.get(W+U);return Y}class k{jg=!1;Tf=[];ig=void 0;xg=0;wg=0;get(q){if(!(q>this.length-1||0>q)){var K=q%this.chunkSize;return this.ig(q/this.chunkSize|0)[K]}}Mg(q){this.ig=q}yg(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);200<=q.status&&300>q.status||304===q.status||r("Couldn't load "+c+". Status: "+q.status);
var K=Number(q.getResponseHeader("Content-length")),X,Y=(X=q.getResponseHeader("Accept-Ranges"))&&"bytes"===X;q=(X=q.getResponseHeader("Content-Encoding"))&&"gzip"===X;var W=1048576;Y||(W=K);var U=this;U.Mg(Na=>{var Ya=Na*W,Oa=(Na+1)*W-1;Oa=Math.min(Oa,K-1);if("undefined"==typeof U.Tf[Na]){var pi=U.Tf;Ya>Oa&&r("invalid range ("+Ya+", "+Oa+") or no bytes requested!");Oa>K-1&&r("only "+K+" bytes available! programmer error!");var Z=new XMLHttpRequest;Z.open("GET",c,!1);K!==W&&Z.setRequestHeader("Range",
"bytes="+Ya+"-"+Oa);Z.responseType="arraybuffer";Z.overrideMimeType&&Z.overrideMimeType("text/plain; charset=x-user-defined");Z.send(null);200<=Z.status&&300>Z.status||304===Z.status||r("Couldn't load "+c+". Status: "+Z.status);Ya=void 0!==Z.response?new Uint8Array(Z.response||[]):eb(Z.responseText||"",!0);pi[Na]=Ya}"undefined"==typeof U.Tf[Na]&&r("doXHR failed!");return U.Tf[Na]});if(q||!K)W=K=1,W=K=this.ig(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");
this.xg=K;this.wg=W;this.jg=!0}get length(){this.jg||this.yg();return this.xg}get chunkSize(){this.jg||this.yg();return this.wg}}if("undefined"!=typeof XMLHttpRequest){ba||r("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var m=new k;var t=void 0}else t=c,m=void 0;var u=Qb(a,b,d,f);m?u.Gf=m:t&&(u.Gf=null,u.url=t);Object.defineProperties(u,{Lf:{get:function(){return this.Gf.length}}});var C={};Object.keys(u.Ff).forEach(q=>{var K=
u.Ff[q];C[q]=(...X)=>{Rb(u);return K(...X)}});C.read=(q,K,X,Y,W)=>{Rb(u);return h(q,K,X,Y,W)};C.ag=(q,K,X)=>{Rb(u);var Y=mb(K);if(!Y)throw new x.Df(48);h(q,g,Y,K,X);return{Cf:Y,zg:!0}};u.Ff=C;return u}
var x={root:null,eg:[],Cg:{},streams:[],ug:1,Rf:null,Bg:"/",qg:!1,Fg:!0,Qg:null,hg:0,Hg:{},Df:class{name="ErrnoError";constructor(a){this.Kf=a}},Lg:class{Tf={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Tf.flags}set flags(a){this.Tf.flags=a}get position(){return this.Tf.position}set position(a){this.Tf.position=a}},Kg:class{Ef={};Ff={};Pf=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Jf=a.Jf;this.id=x.ug++;this.name=b;this.mode=c;this.rdev=d;
this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get sh(){return z(this.mode)}get rh(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new x.Kg(a,b,c,d);Cb(a);return a},sg(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Ng:4096,Sg:a=>x.streams[a],
Og:{open(a){a.Ff=x.Rg(a.node.rdev).Ff;a.Ff.open?.(a)},Mf(){throw new x.Df(70);}},tg:a=>a>>8,Nh:a=>a&255,$f:(a,b)=>a<<8|b,Rg:a=>x.Cg[a],Jg(a,b){function c(k){x.hg--;return b(k)}function d(k){if(k){if(!d.Pg)return d.Pg=!0,c(k)}else++h>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);x.hg++;1<x.hg&&ma(`warning: ${x.hg} FS.syncfs operations in flight at once, probably just doing extra work`);var f=Kb(x.root.Jf),h=0;f.forEach(k=>{if(!k.type.Jg)return d(null);k.type.Jg(k,a,d)})},Jf(a,b,c){var d="/"===
c;if(d&&x.root)throw new x.Df(10);if(!d&&c){var f=A(c,{fg:!1});c=f.path;f=f.node;if(f.Pf)throw new x.Df(10);if(!z(f.mode))throw new x.Df(54);}b={type:a,uh:b,Gg:c,eg:[]};a=a.Jf(b);a.Jf=b;b.root=a;d?x.root=a:f&&(f.Pf=b,f.Jf&&f.Jf.eg.push(b));return a},Th(a){a=A(a,{fg:!1});if(!a.node.Pf)throw new x.Df(28);a=a.node;var b=a.Pf,c=Kb(b);Object.keys(x.Rf).forEach(d=>{for(d=x.Rf[d];d;){var f=d.bg;c.includes(d.Jf)&&ob(d);d=f}});a.Pf=null;a.Jf.eg.splice(a.Jf.eg.indexOf(b),1)},lookup(a,b){return a.Ef.lookup(a,
b)},Vf(a,b,c){var d=A(a,{parent:!0}).node;a=Va(a);if(!a)throw new x.Df(28);if("."===a||".."===a)throw new x.Df(20);var f=Eb(d,a);if(f)throw new x.Df(f);if(!d.Ef.Vf)throw new x.Df(63);return d.Ef.Vf(d,a,b,c)},Ig(a){return Lb(A(a,{Nf:!0}).node)},Sh(a){return Lb(a.node)},create(a,b=438){return x.Vf(a,b&4095|32768,0)},mkdir(a,b=511){return x.Vf(a,b&1023|16384,0)},Oh(a,b){var c=a.split("/"),d="",f;for(f of c)if(f){if(d||"/"===a.charAt(0))d+="/";d+=f;try{x.mkdir(d,b)}catch(h){if(20!=h.Kf)throw h;}}},symlink(a,
b){if(!$a(a))throw new x.Df(44);var c=A(b,{parent:!0}).node;if(!c)throw new x.Df(44);b=Va(b);var d=Eb(c,b);if(d)throw new x.Df(d);if(!c.Ef.symlink)throw new x.Df(63);return c.Ef.symlink(c,b,a)},rename(a,b){var c=Ua(a),d=Ua(b),f=Va(a),h=Va(b);var k=A(a,{parent:!0});var m=k.node;k=A(b,{parent:!0});k=k.node;if(!m||!k)throw new x.Df(44);if(m.Jf!==k.Jf)throw new x.Df(75);var t=nb(m,f);a=ab(a,d);if("."!==a.charAt(0))throw new x.Df(28);a=ab(b,c);if("."!==a.charAt(0))throw new x.Df(55);try{var u=nb(k,h)}catch(C){}if(t!==
u){b=z(t.mode);if(f=Fb(m,f,b))throw new x.Df(f);if(f=u?Fb(k,h,b):Eb(k,h))throw new x.Df(f);if(!m.Ef.rename)throw new x.Df(63);if(t.Pf||u&&u.Pf)throw new x.Df(10);if(k!==m&&(f=zb(m,"w")))throw new x.Df(f);ob(t);try{m.Ef.rename(t,k,h),t.parent=k}catch(C){throw C;}finally{Cb(t)}}},rmdir(a){var b=A(a,{parent:!0}).node;a=Va(a);var c=nb(b,a),d=Fb(b,a,!0);if(d)throw new x.Df(d);if(!b.Ef.rmdir)throw new x.Df(63);if(c.Pf)throw new x.Df(10);b.Ef.rmdir(b,a);ob(c)},readdir(a){a=A(a,{Nf:!0}).node;return Gb(a.Ef.readdir,
54)(a)},unlink(a){var b=A(a,{parent:!0}).node;if(!b)throw new x.Df(44);a=Va(a);var c=nb(b,a),d=Fb(b,a,!1);if(d)throw new x.Df(d);if(!b.Ef.unlink)throw new x.Df(63);if(c.Pf)throw new x.Df(10);b.Ef.unlink(b,a);ob(c)},readlink(a){a=A(a).node;if(!a)throw new x.Df(44);if(!a.Ef.readlink)throw new x.Df(28);return a.Ef.readlink(a)},stat(a,b){a=A(a,{Nf:!b}).node;return Gb(a.Ef.Of,63)(a)},fstat(a){var b=B(a);a=b.node;var c=b.Ff.Of;b=c?b:a;c??=a.Ef.Of;Gb(c,63);return c(b)},lstat(a){return x.stat(a,!0)},chmod(a,
b,c){a="string"==typeof a?A(a,{Nf:!c}).node:a;Nb(null,a,b,c)},lchmod(a,b){x.chmod(a,b,!0)},fchmod(a,b){a=B(a);Nb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?A(a,{Nf:!d}).node:a;Jb(null,a,{timestamp:Date.now(),Dg:d})},lchown(a,b,c){x.chown(a,b,c,!0)},fchown(a){a=B(a);Jb(a,a.node,{timestamp:Date.now(),Dg:!1})},truncate(a,b){if(0>b)throw new x.Df(28);a="string"==typeof a?A(a,{Nf:!0}).node:a;Ob(null,a,b)},Lh(a,b){a=B(a);if(0>b||0===(a.flags&2097155))throw new x.Df(28);Ob(a,a.node,b)},Uh(a,b,c){a=
A(a,{Nf:!0}).node;Gb(a.Ef.Qf,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new x.Df(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var f=a.endsWith("/");a=A(a,{Nf:!(b&131072),th:!0});d=a.node;a=a.path}var h=!1;if(b&64)if(d){if(b&128)throw new x.Df(20);}else{if(f)throw new x.Df(31);d=x.Vf(a,c|511,0);h=!0}if(!d)throw new x.Df(44);
8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!z(d.mode))throw new x.Df(54);if(!h&&(f=d?40960===(d.mode&61440)?32:z(d.mode)&&("r"!==Db(b)||b&576)?31:zb(d,Db(b)):44))throw new x.Df(f);b&512&&!h&&x.truncate(d,0);b&=-131713;f=Hb({node:d,path:Bb(d),flags:b,seekable:!0,position:0,Ff:d.Ff,vh:[],error:!1});f.Ff.open&&f.Ff.open(f);h&&x.chmod(d,c&511);!e.logReadFiles||b&1||a in x.Hg||(x.Hg[a]=1);return f},close(a){if(null===a.fd)throw new x.Df(8);a.pg&&(a.pg=null);try{a.Ff.close&&a.Ff.close(a)}catch(b){throw b;
}finally{x.streams[a.fd]=null}a.fd=null},Mf(a,b,c){if(null===a.fd)throw new x.Df(8);if(!a.seekable||!a.Ff.Mf)throw new x.Df(70);if(0!=c&&1!=c&&2!=c)throw new x.Df(28);a.position=a.Ff.Mf(a,b,c);a.vh=[];return a.position},read(a,b,c,d,f){if(0>d||0>f)throw new x.Df(28);if(null===a.fd)throw new x.Df(8);if(1===(a.flags&2097155))throw new x.Df(8);if(z(a.node.mode))throw new x.Df(31);if(!a.Ff.read)throw new x.Df(28);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new x.Df(70);b=
a.Ff.read(a,b,c,d,f);h||(a.position+=b);return b},write(a,b,c,d,f,h){if(0>d||0>f)throw new x.Df(28);if(null===a.fd)throw new x.Df(8);if(0===(a.flags&2097155))throw new x.Df(8);if(z(a.node.mode))throw new x.Df(31);if(!a.Ff.write)throw new x.Df(28);a.seekable&&a.flags&1024&&x.Mf(a,0,2);var k="undefined"!=typeof f;if(!k)f=a.position;else if(!a.seekable)throw new x.Df(70);b=a.Ff.write(a,b,c,d,f,h);k||(a.position+=b);return b},ag(a,b,c,d,f){if(0!==(d&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new x.Df(2);
if(1===(a.flags&2097155))throw new x.Df(2);if(!a.Ff.ag)throw new x.Df(43);if(!b)throw new x.Df(28);return a.Ff.ag(a,b,c,d,f)},dg(a,b,c,d,f){return a.Ff.dg?a.Ff.dg(a,b,c,d,f):0},rg(a,b,c){if(!a.Ff.rg)throw new x.Df(59);return a.Ff.rg(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&r(`Invalid encoding type "${b.encoding}"`);var c=x.open(a,b.flags);a=x.stat(a).size;var d=new Uint8Array(a);x.read(c,d,0,a,0);"utf8"===b.encoding&&(d=
v(d));x.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=x.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(eb(b,!0)));ArrayBuffer.isView(b)?x.write(a,b,0,b.byteLength,void 0,c.Eh):r("Unsupported data type");x.close(a)},cwd:()=>x.Bg,chdir(a){a=A(a,{Nf:!0});if(null===a.node)throw new x.Df(44);if(!z(a.node.mode))throw new x.Df(54);var b=zb(a.node,"x");if(b)throw new x.Df(b);x.Bg=a.path},gg(a,b,c){x.qg=!0;a??=e.stdin;b??=e.stdout;c??=e.stderr;a?x.Xf("/dev","stdin",a):x.symlink("/dev/tty",
"/dev/stdin");b?x.Xf("/dev","stdout",null,b):x.symlink("/dev/tty","/dev/stdout");c?x.Xf("/dev","stderr",null,c):x.symlink("/dev/tty1","/dev/stderr");x.open("/dev/stdin",0);x.open("/dev/stdout",1);x.open("/dev/stderr",1)},Rh(){x.qg=!1;for(var a of x.streams)a&&x.close(a)},Ih(a,b){try{var c=A(a,{Nf:!b});a=c.path}catch(h){}var d=!1,f=null;try{c=A(a,{parent:!0}),Va(a),c=A(a,{Nf:!b}),d=!0,f=c.node}catch(h){}return d?f:null},Xf(a,b,c,d){a=Wa("string"==typeof a?a:Bb(a),b);b=pb(!!c,!!d);var f;(f=x.Xf).tg??
(f.tg=64);f=x.$f(x.Xf.tg++,0);hb(f,{open(h){h.seekable=!1},close(){d?.buffer?.length&&d(10)},read(h,k,m,t){for(var u=0,C=0;C<t;C++){try{var q=c()}catch(K){throw new x.Df(29);}if(void 0===q&&0===u)throw new x.Df(6);if(null===q||void 0===q)break;u++;k[m+C]=q}u&&(h.node.atime=Date.now());return u},write(h,k,m,t){for(var u=0;u<t;u++)try{d(k[m+u])}catch(C){throw new x.Df(29);}t&&(h.node.mtime=h.node.ctime=Date.now());return u}});return Mb(a,b,f)}};
function Tb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?x.cwd():B(a).path;if(0==b.length){if(!c)throw new x.Df(44);return a}return a+"/"+b}
function Ub(a,b){p[a>>2]=b.dev;p[a+4>>2]=b.mode;p[a+8>>2]=b.nlink;p[a+12>>2]=b.uid;p[a+16>>2]=b.gid;p[a+20>>2]=b.rdev;va[a+24>>3]=BigInt(b.size);n[a+32>>2]=4096;n[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),f=b.ctime.getTime();va[a+40>>3]=BigInt(Math.floor(c/1E3));p[a+48>>2]=c%1E3*1E6;va[a+56>>3]=BigInt(Math.floor(d/1E3));p[a+64>>2]=d%1E3*1E6;va[a+72>>3]=BigInt(Math.floor(f/1E3));p[a+80>>2]=f%1E3*1E6;va[a+88>>3]=BigInt(b.ino);return 0}
var Qa=void 0,Vb=a=>0===a%4&&(0!==a%100||0===a%400),Wb=[0,31,60,91,121,152,182,213,244,274,305,335],Xb=[0,31,59,90,120,151,181,212,243,273,304,334],Yb=[],Zb={},ac=()=>{if(!$b){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Zb)void 0===Zb[b]?delete a[b]:a[b]=Zb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);$b=c}return $b},$b,bc=[],cc,dc=a=>{var b=
bc[a];b||(bc[a]=b=cc.get(a));return b};x.Fh=(a,b,c,d,f,h,k,m,t,u)=>{yb(a,b,c,d,f,m,t,u).then(h).catch(k)};x.Qh=yb;x.Rf=Array(4096);x.Jf(y,{},"/");x.mkdir("/tmp");x.mkdir("/home");x.mkdir("/home/web_user");
(function(){x.mkdir("/dev");hb(x.$f(1,3),{read:()=>0,write:(d,f,h,k)=>k,Mf:()=>0});Mb("/dev/null",x.$f(1,3));gb(x.$f(5,0),jb);gb(x.$f(6,0),kb);Mb("/dev/tty",x.$f(5,0));Mb("/dev/tty1",x.$f(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Za(a),b=a.byteLength);return a[--b]};x.Xf("/dev","random",c);x.Xf("/dev","urandom",c);x.mkdir("/dev/shm");x.mkdir("/dev/shm/tmp")})();
(function(){x.mkdir("/proc");var a=x.mkdir("/proc/self");x.mkdir("/proc/self/fd");x.Jf({Jf(){var b=x.createNode(a,"fd",16895,73);b.Ff={Mf:y.Ff.Mf};b.Ef={lookup(c,d){c=+d;var f=B(c);c={parent:null,Jf:{Gg:"fake"},Ef:{readlink:()=>f.path},id:c+1};return c.parent=c},readdir(){return Array.from(x.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();x.Qg={MEMFS:y};e.noExitRuntime&&(Ia=e.noExitRuntime);e.preloadPlugins&&(vb=e.preloadPlugins);e.print&&(la=e.print);
e.printErr&&(ma=e.printErr);e.wasmBinary&&(na=e.wasmBinary);e.thisProgram&&(da=e.thisProgram);if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();e.addRunDependency=ub;e.removeRunDependency=tb;e.setValue=Ja;e.getValue=Ha;e.FS_preloadFile=yb;e.FS_unlink=(...a)=>x.unlink(...a);e.FS_createPath=(...a)=>Pb(...a);e.FS_createDevice=(...a)=>x.Xf(...a);e.FS=x;e.FS_createDataFile=(...a)=>xb(...a);e.FS_createLazyFile=(...a)=>Sb(...a);
var ec={633484:a=>{e.TesseractProgress&&e.TesseractProgress(a)},633553:a=>{e.TesseractProgress&&e.TesseractProgress(a)},633622:a=>{e.TesseractProgress&&e.TesseractProgress(a)}},fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,
ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf,Mf,Nf,Of,Pf,Qf,Rf,Sf,Tf,Uf,Vf,Wf,Xf,Yf,Zf,$f,ag,bg,cg,dg,eg,fg,gg,hg,ig,jg,kg,lg,mg,ng,og,pg,qg,rg,sg,tg,ug,vg,wg,xg,yg,zg,Ag,Bg,Cg,Dg,Eg,Fg,Gg,Hg,Ig,Jg,Kg,Lg,Mg,Ng,Og,Pg,Qg,Rg,Sg,Tg,Ug,Vg,Wg,Xg,Yg,Zg,$g,ah,bh,ch,dh,eh,fh,gh,hh,ih,jh,kh,lh,mh,nh,oh,ph,qh,
rh,sh,th,uh,vh,wh,xh,yh,zh,Ah,Bh,Ch,Dh,Eh,Fh,Gh,Hh,Ih,Jh,Kh,Lh,Mh,lb,Nh,Oh,Ph,ai={a:(a,b,c,d)=>r(`Assertion failed: ${a?v(l,a):""}, at: `+[b?b?v(l,b):"":"unknown filename",c,d?d?v(l,d):"":"unknown function"]),l:(a,b,c)=>{(new La(a)).gg(b,c);Ma=a;Pa++;throw Ma;},r:function(a,b,c){Qa=c;try{var d=B(a);switch(b){case 0:var f=Ra();if(0>f)break;for(;x.streams[f];)f++;return Ib(d,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Ra(),d.flags|=f,0;case 12:return f=Ra(),sa[f+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(h){if("undefined"==
typeof x||"ErrnoError"!==h.name)throw h;return-h.Kf}},J:function(a,b){try{return Ub(b,x.fstat(a))}catch(c){if("undefined"==typeof x||"ErrnoError"!==c.name)throw c;return-c.Kf}},H:function(a,b){try{if(0===b)return-28;var c=x.cwd(),d=cb(c)+1;if(b<d)return-68;db(c,l,a,b);return d}catch(f){if("undefined"==typeof x||"ErrnoError"!==f.name)throw f;return-f.Kf}},N:function(a,b,c){Qa=c;try{var d=B(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Wf.oh){a=[3,28,127,21,4,0,
1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var f=Ra();n[f>>2]=25856;n[f+4>>2]=5;n[f+8>>2]=191;n[f+12>>2]=35387;for(var h=0;32>h;h++)g[f+h+17]=a[h]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Wf.ph)for(f=Ra(),a=[],h=0;32>h;h++)a.push(g[f+h+17]);return 0;case 21519:if(!d.tty)return-59;f=Ra();return n[f>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return f=Ra(),x.rg(d,b,f);case 21523:if(!d.tty)return-59;
d.tty.Wf.qh&&(h=[24,80],f=Ra(),sa[f>>1]=h[0],sa[f+2>>1]=h[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(k){if("undefined"==typeof x||"ErrnoError"!==k.name)throw k;return-k.Kf}},I:function(a,b,c,d){try{b=b?v(l,b):"";var f=d&256;b=Tb(a,b,d&4096);return Ub(c,f?x.lstat(b):x.stat(b))}catch(h){if("undefined"==typeof x||"ErrnoError"!==h.name)throw h;return-h.Kf}},p:function(a,b,c,d){Qa=d;try{b=b?v(l,b):"";b=Tb(a,b);var f=d?Ra():0;return x.open(b,c,f).fd}catch(h){if("undefined"==
typeof x||"ErrnoError"!==h.name)throw h;return-h.Kf}},w:function(a){try{return a=a?v(l,a):"",x.rmdir(a),0}catch(b){if("undefined"==typeof x||"ErrnoError"!==b.name)throw b;return-b.Kf}},x:function(a,b,c){try{b=b?v(l,b):"";b=Tb(a,b);if(c)if(512===c)x.rmdir(b);else return-28;else x.unlink(b);return 0}catch(d){if("undefined"==typeof x||"ErrnoError"!==d.name)throw d;return-d.Kf}},M:()=>r(""),O:a=>{do{var b=p[a>>2];a+=4;var c=p[a>>2];a+=4;var d=p[a>>2];a+=4;b=b?v(l,b):"";Pb("/",Ua(b));xb(b,null,g.subarray(d,
d+c),!0,!0,!0)}while(p[a>>2])},u:()=>{throw Infinity;},A:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);n[b>>2]=a.getUTCSeconds();n[b+4>>2]=a.getUTCMinutes();n[b+8>>2]=a.getUTCHours();n[b+12>>2]=a.getUTCDate();n[b+16>>2]=a.getUTCMonth();n[b+20>>2]=a.getUTCFullYear()-1900;n[b+24>>2]=a.getUTCDay();n[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},B:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);
n[b>>2]=a.getSeconds();n[b+4>>2]=a.getMinutes();n[b+8>>2]=a.getHours();n[b+12>>2]=a.getDate();n[b+16>>2]=a.getMonth();n[b+20>>2]=a.getFullYear()-1900;n[b+24>>2]=a.getDay();n[b+28>>2]=(Vb(a.getFullYear())?Wb:Xb)[a.getMonth()]+a.getDate()-1|0;n[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();n[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},C:function(a){var b=new Date(n[a+20>>2]+1900,n[a+16>>
2],n[a+12>>2],n[a+8>>2],n[a+4>>2],n[a>>2],0),c=n[a+32>>2],d=b.getTimezoneOffset(),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(h,f);0>c?n[a+32>>2]=Number(f!=h&&k==d):0<c!=(k==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?k:f)-d)));n[a+24>>2]=b.getDay();n[a+28>>2]=(Vb(b.getFullYear())?Wb:Xb)[b.getMonth()]+b.getDate()-1|0;n[a>>2]=b.getSeconds();n[a+4>>2]=b.getMinutes();n[a+8>>2]=b.getHours();n[a+12>>2]=b.getDate();n[a+
16>>2]=b.getMonth();n[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},y:function(a,b,c,d,f,h,k){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var m=B(d),t=x.ag(m,a,f,b,c),u=t.Cf;n[h>>2]=t.zg;p[k>>2]=u;return 0}catch(C){if("undefined"==typeof x||"ErrnoError"!==C.name)throw C;return-C.Kf}},z:function(a,b,c,d,f,h){h=-9007199254740992>h||9007199254740992<h?NaN:Number(h);try{var k=B(f);if(c&2){c=h;if(!x.isFile(k.node.mode))throw new x.Df(43);if(!(d&2)){var m=l.slice(a,
a+b);x.dg(k,m,c,b,d)}}}catch(t){if("undefined"==typeof x||"ErrnoError"!==t.name)throw t;return-t.Kf}},D:(a,b,c,d)=>{var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();p[a>>2]=60*Math.max(h,f);n[b>>2]=Number(h!=f);b=k=>{var m=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(db(a,l,c,17),db(b,l,d,17)):(db(a,l,d,17),db(b,l,c,17))},L:function(a,b,c){if(!(0<=a&&
3>=a))return 28;va[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},o:(a,b,c)=>{Yb.length=0;for(var d;d=l[b++];){var f=105!=d;f&=112!=d;c+=f&&c%8?4:0;Yb.push(112==d?p[c>>2]:106==d?va[c>>3]:105==d?n[c>>2]:ua[c>>3]);c+=f?8:4}return ec[a](...Yb)},K:()=>Date.now(),v:a=>{var b=l.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|
0;try{ra.grow(d);xa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},F:(a,b)=>{var c=0,d=0,f;for(f of ac()){var h=b+c;p[a+d>>2]=h;c+=db(f,l,h,Infinity)+1;d+=4}return 0},G:(a,b)=>{var c=ac();p[a>>2]=c.length;a=0;for(var d of c)a+=cb(d)+1;p[b>>2]=a;return 0},k:a=>{Ia||(e.onExit?.(a),oa=!0);ea(a,new Ca(a))},n:function(a){try{var b=B(a);x.close(b);return 0}catch(c){if("undefined"==typeof x||"ErrnoError"!==c.name)throw c;return c.Kf}},q:function(a,b,c,d){try{a:{var f=B(a);a=b;for(var h,k=b=
0;k<c;k++){var m=p[a>>2],t=p[a+4>>2];a+=8;var u=x.read(f,g,m,t,h);if(0>u){var C=-1;break a}b+=u;if(u<t)break;"undefined"!=typeof h&&(h+=u)}C=b}p[d>>2]=C;return 0}catch(q){if("undefined"==typeof x||"ErrnoError"!==q.name)throw q;return q.Kf}},E:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var f=B(a);x.Mf(f,b,c);va[d>>3]=BigInt(f.position);f.pg&&0===b&&0===c&&(f.pg=null);return 0}catch(h){if("undefined"==typeof x||"ErrnoError"!==h.name)throw h;return h.Kf}},
m:function(a,b,c,d){try{a:{var f=B(a);a=b;for(var h,k=b=0;k<c;k++){var m=p[a>>2],t=p[a+4>>2];a+=8;var u=x.write(f,g,m,t,h);if(0>u){var C=-1;break a}b+=u;if(u<t)break;"undefined"!=typeof h&&(h+=u)}C=b}p[d>>2]=C;return 0}catch(q){if("undefined"==typeof x||"ErrnoError"!==q.name)throw q;return q.Kf}},c:Qh,e:Rh,b:Sh,h:Th,i:Uh,d:Vh,f:Wh,g:Xh,j:Yh,s:Zh,t:$h};function Sh(a,b,c,d){var f=Ph();try{return dc(a)(b,c,d)}catch(h){Oh(f);if(h!==h+0)throw h;Nh(1,0)}}
function Vh(a,b){var c=Ph();try{dc(a)(b)}catch(d){Oh(c);if(d!==d+0)throw d;Nh(1,0)}}function Qh(a,b){var c=Ph();try{return dc(a)(b)}catch(d){Oh(c);if(d!==d+0)throw d;Nh(1,0)}}function Xh(a,b,c,d){var f=Ph();try{dc(a)(b,c,d)}catch(h){Oh(f);if(h!==h+0)throw h;Nh(1,0)}}function Wh(a,b,c){var d=Ph();try{dc(a)(b,c)}catch(f){Oh(d);if(f!==f+0)throw f;Nh(1,0)}}function Rh(a,b,c){var d=Ph();try{return dc(a)(b,c)}catch(f){Oh(d);if(f!==f+0)throw f;Nh(1,0)}}
function Th(a,b,c,d,f){var h=Ph();try{return dc(a)(b,c,d,f)}catch(k){Oh(h);if(k!==k+0)throw k;Nh(1,0)}}function Yh(a,b,c,d,f){var h=Ph();try{dc(a)(b,c,d,f)}catch(k){Oh(h);if(k!==k+0)throw k;Nh(1,0)}}function Uh(a,b,c,d,f,h){var k=Ph();try{return dc(a)(b,c,d,f,h)}catch(m){Oh(k);if(m!==m+0)throw m;Nh(1,0)}}function $h(a,b,c,d,f,h,k,m,t,u){var C=Ph();try{dc(a)(b,c,d,f,h,k,m,t,u)}catch(q){Oh(C);if(q!==q+0)throw q;Nh(1,0)}}
function Zh(a,b,c,d,f,h){var k=Ph();try{dc(a)(b,c,d,f,h)}catch(m){Oh(k);if(m!==m+0)throw m;Nh(1,0)}}
function bi(){function a(){e.calledRun=!0;if(!oa){wa=!0;e.noFSInit||x.qg||x.gg();ci.Q();x.Fg=!1;pa?.(e);e.onRuntimeInitialized?.();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ea.push(b)}Da(Ea)}}if(0<rb)sb=bi;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ga();Da(Fa);0<rb?sb=bi:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);a()},1)):a()}}var ci;
ci=await (async function(){function a(c){ci=c.exports;ra=ci.P;xa();cc=ci.$;c=ci;e._emscripten_bind_ParagraphJustification___destroy___0=fc=c.R;e._emscripten_bind_BoolPtr___destroy___0=gc=c.S;e._emscripten_bind_TessResultRenderer_BeginDocument_1=hc=c.T;e._emscripten_bind_TessResultRenderer_AddImage_1=ic=c.U;e._emscripten_bind_TessResultRenderer_EndDocument_0=jc=c.V;e._emscripten_bind_TessResultRenderer_happy_0=kc=c.W;e._emscripten_bind_TessResultRenderer_file_extension_0=lc=c.X;e._emscripten_bind_TessResultRenderer_title_0=
mc=c.Y;e._emscripten_bind_TessResultRenderer_imagenum_0=nc=c.Z;e._emscripten_bind_TessResultRenderer___destroy___0=oc=c._;e._emscripten_bind_LongStarPtr___destroy___0=pc=c.aa;e._emscripten_bind_VoidPtr___destroy___0=qc=c.ba;e._emscripten_bind_ResultIterator_ResultIterator_1=rc=c.ca;e._emscripten_bind_ResultIterator_Begin_0=sc=c.da;e._emscripten_bind_ResultIterator_RestartParagraph_0=tc=c.ea;e._emscripten_bind_ResultIterator_IsWithinFirstTextlineOfParagraph_0=uc=c.fa;e._emscripten_bind_ResultIterator_RestartRow_0=
vc=c.ga;e._emscripten_bind_ResultIterator_Next_1=wc=c.ha;e._emscripten_bind_ResultIterator_IsAtBeginningOf_1=xc=c.ia;e._emscripten_bind_ResultIterator_IsAtFinalElement_2=yc=c.ja;e._emscripten_bind_ResultIterator_Cmp_1=zc=c.ka;e._emscripten_bind_ResultIterator_SetBoundingBoxComponents_2=Ac=c.la;e._emscripten_bind_ResultIterator_BoundingBox_5=Bc=c.ma;e._emscripten_bind_ResultIterator_BoundingBox_6=Cc=c.na;e._emscripten_bind_ResultIterator_BoundingBoxInternal_5=Dc=c.oa;e._emscripten_bind_ResultIterator_Empty_1=
Ec=c.pa;e._emscripten_bind_ResultIterator_BlockType_0=Fc=c.qa;e._emscripten_bind_ResultIterator_BlockPolygon_0=Gc=c.ra;e._emscripten_bind_ResultIterator_GetBinaryImage_1=Hc=c.sa;e._emscripten_bind_ResultIterator_GetImage_5=Ic=c.ta;e._emscripten_bind_ResultIterator_Baseline_5=Jc=c.ua;e._emscripten_bind_ResultIterator_RowAttributes_3=Kc=c.va;e._emscripten_bind_ResultIterator_Orientation_4=Lc=c.wa;e._emscripten_bind_ResultIterator_ParagraphInfo_4=Mc=c.xa;e._emscripten_bind_ResultIterator_ParagraphIsLtr_0=
Nc=c.ya;e._emscripten_bind_ResultIterator_GetUTF8Text_1=Oc=c.za;e._emscripten_bind_ResultIterator_SetLineSeparator_1=Pc=c.Aa;e._emscripten_bind_ResultIterator_SetParagraphSeparator_1=Qc=c.Ba;e._emscripten_bind_ResultIterator_Confidence_1=Rc=c.Ca;e._emscripten_bind_ResultIterator_WordFontAttributes_8=Sc=c.Da;e._emscripten_bind_ResultIterator_WordRecognitionLanguage_0=Tc=c.Ea;e._emscripten_bind_ResultIterator_WordDirection_0=Uc=c.Fa;e._emscripten_bind_ResultIterator_WordIsFromDictionary_0=Vc=c.Ga;e._emscripten_bind_ResultIterator_WordIsNumeric_0=
Wc=c.Ha;e._emscripten_bind_ResultIterator_HasBlamerInfo_0=Xc=c.Ia;e._emscripten_bind_ResultIterator_HasTruthString_0=Yc=c.Ja;e._emscripten_bind_ResultIterator_EquivalentToTruth_1=Zc=c.Ka;e._emscripten_bind_ResultIterator_WordTruthUTF8Text_0=$c=c.La;e._emscripten_bind_ResultIterator_WordNormedUTF8Text_0=ad=c.Ma;e._emscripten_bind_ResultIterator_WordLattice_1=bd=c.Na;e._emscripten_bind_ResultIterator_SymbolIsSuperscript_0=cd=c.Oa;e._emscripten_bind_ResultIterator_SymbolIsSubscript_0=dd=c.Pa;e._emscripten_bind_ResultIterator_SymbolIsDropcap_0=
ed=c.Qa;e._emscripten_bind_ResultIterator___destroy___0=fd=c.Ra;e._emscripten_bind_TextlineOrder___destroy___0=gd=c.Sa;e._emscripten_bind_ETEXT_DESC___destroy___0=hd=c.Ta;e._emscripten_bind_PageIterator_Begin_0=jd=c.Ua;e._emscripten_bind_PageIterator_RestartParagraph_0=kd=c.Va;e._emscripten_bind_PageIterator_IsWithinFirstTextlineOfParagraph_0=ld=c.Wa;e._emscripten_bind_PageIterator_RestartRow_0=md=c.Xa;e._emscripten_bind_PageIterator_Next_1=nd=c.Ya;e._emscripten_bind_PageIterator_IsAtBeginningOf_1=
od=c.Za;e._emscripten_bind_PageIterator_IsAtFinalElement_2=pd=c._a;e._emscripten_bind_PageIterator_Cmp_1=qd=c.$a;e._emscripten_bind_PageIterator_SetBoundingBoxComponents_2=rd=c.ab;e._emscripten_bind_PageIterator_BoundingBox_5=sd=c.bb;e._emscripten_bind_PageIterator_BoundingBox_6=td=c.cb;e._emscripten_bind_PageIterator_BoundingBoxInternal_5=ud=c.db;e._emscripten_bind_PageIterator_Empty_1=vd=c.eb;e._emscripten_bind_PageIterator_BlockType_0=wd=c.fb;e._emscripten_bind_PageIterator_BlockPolygon_0=xd=c.gb;
e._emscripten_bind_PageIterator_GetBinaryImage_1=yd=c.hb;e._emscripten_bind_PageIterator_GetImage_5=zd=c.ib;e._emscripten_bind_PageIterator_Baseline_5=Ad=c.jb;e._emscripten_bind_PageIterator_Orientation_4=Bd=c.kb;e._emscripten_bind_PageIterator_ParagraphInfo_4=Cd=c.lb;e._emscripten_bind_PageIterator___destroy___0=Dd=c.mb;e._emscripten_bind_WritingDirection___destroy___0=Ed=c.nb;e._emscripten_bind_WordChoiceIterator_WordChoiceIterator_1=Fd=c.ob;e._emscripten_bind_WordChoiceIterator_Next_0=Gd=c.pb;
e._emscripten_bind_WordChoiceIterator_GetUTF8Text_0=Hd=c.qb;e._emscripten_bind_WordChoiceIterator_Confidence_0=Id=c.rb;e._emscripten_bind_WordChoiceIterator___destroy___0=Jd=c.sb;e._emscripten_bind_Box_get_x_0=Kd=c.tb;e._emscripten_bind_Box_get_y_0=Ld=c.ub;e._emscripten_bind_Box_get_w_0=Md=c.vb;e._emscripten_bind_Box_get_h_0=Nd=c.wb;e._emscripten_bind_Box_get_refcount_0=Od=c.xb;e._emscripten_bind_Box___destroy___0=Pd=c.yb;e._emscripten_bind_TessPDFRenderer_TessPDFRenderer_3=Qd=c.zb;e._emscripten_bind_TessPDFRenderer_BeginDocument_1=
Rd=c.Ab;e._emscripten_bind_TessPDFRenderer_AddImage_1=Sd=c.Bb;e._emscripten_bind_TessPDFRenderer_EndDocument_0=Td=c.Cb;e._emscripten_bind_TessPDFRenderer_happy_0=Ud=c.Db;e._emscripten_bind_TessPDFRenderer_file_extension_0=Vd=c.Eb;e._emscripten_bind_TessPDFRenderer_title_0=Wd=c.Fb;e._emscripten_bind_TessPDFRenderer_imagenum_0=Xd=c.Gb;e._emscripten_bind_TessPDFRenderer___destroy___0=Yd=c.Hb;e._emscripten_bind_PixaPtr___destroy___0=Zd=c.Ib;e._emscripten_bind_FloatPtr___destroy___0=$d=c.Jb;e._emscripten_bind_ChoiceIterator_ChoiceIterator_1=
ae=c.Kb;e._emscripten_bind_ChoiceIterator_Next_0=be=c.Lb;e._emscripten_bind_ChoiceIterator_GetUTF8Text_0=ce=c.Mb;e._emscripten_bind_ChoiceIterator_Confidence_0=de=c.Nb;e._emscripten_bind_ChoiceIterator___destroy___0=ee=c.Ob;e._emscripten_bind_PixPtr___destroy___0=fe=c.Pb;e._emscripten_bind_UNICHARSET_get_script_from_script_id_1=ge=c.Qb;e._emscripten_bind_UNICHARSET_get_script_id_from_name_1=he=c.Rb;e._emscripten_bind_UNICHARSET_get_script_table_size_0=ie=c.Sb;e._emscripten_bind_UNICHARSET___destroy___0=
je=c.Tb;e._emscripten_bind_IntPtr___destroy___0=ke=c.Ub;e._emscripten_bind_Orientation___destroy___0=le=c.Vb;e._emscripten_bind_OSBestResult_get_orientation_id_0=me=c.Wb;e._emscripten_bind_OSBestResult_get_script_id_0=ne=c.Xb;e._emscripten_bind_OSBestResult_get_sconfidence_0=oe=c.Yb;e._emscripten_bind_OSBestResult_get_oconfidence_0=pe=c.Zb;e._emscripten_bind_OSBestResult___destroy___0=qe=c._b;e._emscripten_bind_Boxa_get_n_0=re=c.$b;e._emscripten_bind_Boxa_get_nalloc_0=se=c.ac;e._emscripten_bind_Boxa_get_refcount_0=
te=c.bc;e._emscripten_bind_Boxa_get_box_0=ue=c.cc;e._emscripten_bind_Boxa___destroy___0=ve=c.dc;e._emscripten_bind_PixColormap_get_array_0=we=c.ec;e._emscripten_bind_PixColormap_get_depth_0=xe=c.fc;e._emscripten_bind_PixColormap_get_nalloc_0=ye=c.gc;e._emscripten_bind_PixColormap_get_n_0=ze=c.hc;e._emscripten_bind_PixColormap___destroy___0=Ae=c.ic;e._emscripten_bind_Pta_get_n_0=Be=c.jc;e._emscripten_bind_Pta_get_nalloc_0=Ce=c.kc;e._emscripten_bind_Pta_get_refcount_0=De=c.lc;e._emscripten_bind_Pta_get_x_0=
Ee=c.mc;e._emscripten_bind_Pta_get_y_0=Fe=c.nc;e._emscripten_bind_Pta___destroy___0=Ge=c.oc;e._emscripten_bind_Pix_get_w_0=He=c.pc;e._emscripten_bind_Pix_get_h_0=Ie=c.qc;e._emscripten_bind_Pix_get_d_0=Je=c.rc;e._emscripten_bind_Pix_get_spp_0=Ke=c.sc;e._emscripten_bind_Pix_get_wpl_0=Le=c.tc;e._emscripten_bind_Pix_get_refcount_0=Me=c.uc;e._emscripten_bind_Pix_get_xres_0=Ne=c.vc;e._emscripten_bind_Pix_get_yres_0=Oe=c.wc;e._emscripten_bind_Pix_get_informat_0=Pe=c.xc;e._emscripten_bind_Pix_get_special_0=
Qe=c.yc;e._emscripten_bind_Pix_get_text_0=Re=c.zc;e._emscripten_bind_Pix_get_colormap_0=Se=c.Ac;e._emscripten_bind_Pix_get_data_0=Te=c.Bc;e._emscripten_bind_Pix___destroy___0=Ue=c.Cc;e._emscripten_bind_DoublePtr___destroy___0=Ve=c.Dc;e._emscripten_bind_Dawg___destroy___0=We=c.Ec;e._emscripten_bind_BoxPtr___destroy___0=Xe=c.Fc;e._emscripten_bind_TessBaseAPI_TessBaseAPI_0=Ye=c.Gc;e._emscripten_bind_TessBaseAPI_Version_0=Ze=c.Hc;e._emscripten_bind_TessBaseAPI_SetInputName_1=$e=c.Ic;e._emscripten_bind_TessBaseAPI_GetInputName_0=
af=c.Jc;e._emscripten_bind_TessBaseAPI_SetInputImage_1=bf=c.Kc;e._emscripten_bind_TessBaseAPI_GetInputImage_0=cf=c.Lc;e._emscripten_bind_TessBaseAPI_GetSourceYResolution_0=df=c.Mc;e._emscripten_bind_TessBaseAPI_GetDatapath_0=ef=c.Nc;e._emscripten_bind_TessBaseAPI_SetOutputName_1=ff=c.Oc;e._emscripten_bind_TessBaseAPI_SetVariable_2=gf=c.Pc;e._emscripten_bind_TessBaseAPI_SetDebugVariable_2=hf=c.Qc;e._emscripten_bind_TessBaseAPI_GetIntVariable_2=jf=c.Rc;e._emscripten_bind_TessBaseAPI_GetBoolVariable_2=
kf=c.Sc;e._emscripten_bind_TessBaseAPI_GetDoubleVariable_2=lf=c.Tc;e._emscripten_bind_TessBaseAPI_GetStringVariable_1=mf=c.Uc;e._emscripten_bind_TessBaseAPI_SaveParameters_1=nf=c.Vc;e._emscripten_bind_TessBaseAPI_RestoreParameters_1=of=c.Wc;e._emscripten_bind_TessBaseAPI_Init_2=pf=c.Xc;e._emscripten_bind_TessBaseAPI_Init_3=qf=c.Yc;e._emscripten_bind_TessBaseAPI_Init_4=rf=c.Zc;e._emscripten_bind_TessBaseAPI_GetInitLanguagesAsString_0=sf=c._c;e._emscripten_bind_TessBaseAPI_InitForAnalysePage_0=tf=c.$c;
e._emscripten_bind_TessBaseAPI_ReadConfigFile_1=uf=c.ad;e._emscripten_bind_TessBaseAPI_ReadDebugConfigFile_1=vf=c.bd;e._emscripten_bind_TessBaseAPI_SetPageSegMode_1=wf=c.cd;e._emscripten_bind_TessBaseAPI_GetPageSegMode_0=xf=c.dd;e._emscripten_bind_TessBaseAPI_TesseractRect_7=yf=c.ed;e._emscripten_bind_TessBaseAPI_ClearAdaptiveClassifier_0=zf=c.fd;e._emscripten_bind_TessBaseAPI_PopulateLearningReferenceFromCurrentResult_0=Af=c.gd;e._emscripten_bind_TessBaseAPI_ClearLearningReferenceWords_0=Bf=c.hd;
e._emscripten_bind_TessBaseAPI_SetImage_1=Cf=c.id;e._emscripten_bind_TessBaseAPI_SetImage_5=Df=c.jd;e._emscripten_bind_TessBaseAPI_SetImageFile_1=Ef=c.kd;e._emscripten_bind_TessBaseAPI_SetSourceResolution_1=Ff=c.ld;e._emscripten_bind_TessBaseAPI_SetRectangle_4=Gf=c.md;e._emscripten_bind_TessBaseAPI_GetThresholdedImage_0=Hf=c.nd;e._emscripten_bind_TessBaseAPI_WriteImage_0=If=c.od;e._emscripten_bind_TessBaseAPI_FindLines_0=Jf=c.pd;e._emscripten_bind_TessBaseAPI_GetGradient_0=Kf=c.qd;e._emscripten_bind_TessBaseAPI_GetEstimatedResolution_0=
Lf=c.rd;e._emscripten_bind_TessBaseAPI_GetRegions_1=Mf=c.sd;e._emscripten_bind_TessBaseAPI_GetTextlines_2=Nf=c.td;e._emscripten_bind_TessBaseAPI_GetTextlines_5=Of=c.ud;e._emscripten_bind_TessBaseAPI_GetStrips_2=Pf=c.vd;e._emscripten_bind_TessBaseAPI_GetWords_1=Qf=c.wd;e._emscripten_bind_TessBaseAPI_GetConnectedComponents_1=Rf=c.xd;e._emscripten_bind_TessBaseAPI_GetComponentImages_4=Sf=c.yd;e._emscripten_bind_TessBaseAPI_GetComponentImages_7=Tf=c.zd;e._emscripten_bind_TessBaseAPI_GetThresholdedImageScaleFactor_0=
Uf=c.Ad;e._emscripten_bind_TessBaseAPI_AnalyseLayout_0=Vf=c.Bd;e._emscripten_bind_TessBaseAPI_AnalyseLayout_1=Wf=c.Cd;e._emscripten_bind_TessBaseAPI_Recognize_1=Xf=c.Dd;e._emscripten_bind_TessBaseAPI_ProcessPages_4=Yf=c.Ed;e._emscripten_bind_TessBaseAPI_ProcessPage_6=Zf=c.Fd;e._emscripten_bind_TessBaseAPI_GetIterator_0=$f=c.Gd;e._emscripten_bind_TessBaseAPI_GetUTF8Text_0=ag=c.Hd;e._emscripten_bind_TessBaseAPI_GetHOCRText_1=bg=c.Id;e._emscripten_bind_TessBaseAPI_GetJSONText_1=cg=c.Jd;e._emscripten_bind_TessBaseAPI_GetTSVText_1=
dg=c.Kd;e._emscripten_bind_TessBaseAPI_GetBoxText_1=eg=c.Ld;e._emscripten_bind_TessBaseAPI_GetUNLVText_0=fg=c.Md;e._emscripten_bind_TessBaseAPI_GetOsdText_1=gg=c.Nd;e._emscripten_bind_TessBaseAPI_MeanTextConf_0=hg=c.Od;e._emscripten_bind_TessBaseAPI_AllWordConfidences_0=ig=c.Pd;e._emscripten_bind_TessBaseAPI_Clear_0=jg=c.Qd;e._emscripten_bind_TessBaseAPI_End_0=kg=c.Rd;e._emscripten_bind_TessBaseAPI_ClearPersistentCache_0=lg=c.Sd;e._emscripten_bind_TessBaseAPI_IsValidWord_1=mg=c.Td;e._emscripten_bind_TessBaseAPI_IsValidCharacter_1=
ng=c.Ud;e._emscripten_bind_TessBaseAPI_DetectOS_1=og=c.Vd;e._emscripten_bind_TessBaseAPI_GetUnichar_1=pg=c.Wd;e._emscripten_bind_TessBaseAPI_GetDawg_1=qg=c.Xd;e._emscripten_bind_TessBaseAPI_NumDawgs_0=rg=c.Yd;e._emscripten_bind_TessBaseAPI_oem_0=sg=c.Zd;e._emscripten_bind_TessBaseAPI___destroy___0=tg=c._d;e._emscripten_bind_OSResults_OSResults_0=ug=c.$d;e._emscripten_bind_OSResults_print_scores_0=vg=c.ae;e._emscripten_bind_OSResults_get_best_result_0=wg=c.be;e._emscripten_bind_OSResults_get_unicharset_0=
xg=c.ce;e._emscripten_bind_OSResults___destroy___0=yg=c.de;e._emscripten_bind_Pixa_get_n_0=zg=c.ee;e._emscripten_bind_Pixa_get_nalloc_0=Ag=c.fe;e._emscripten_bind_Pixa_get_refcount_0=Bg=c.ge;e._emscripten_bind_Pixa_get_pix_0=Cg=c.he;e._emscripten_bind_Pixa_get_boxa_0=Dg=c.ie;e._emscripten_bind_Pixa___destroy___0=Eg=c.je;e._emscripten_enum_PageIteratorLevel_RIL_BLOCK=Fg=c.ke;e._emscripten_enum_PageIteratorLevel_RIL_PARA=Gg=c.le;e._emscripten_enum_PageIteratorLevel_RIL_TEXTLINE=Hg=c.me;e._emscripten_enum_PageIteratorLevel_RIL_WORD=
Ig=c.ne;e._emscripten_enum_PageIteratorLevel_RIL_SYMBOL=Jg=c.oe;e._emscripten_enum_OcrEngineMode_OEM_TESSERACT_ONLY=Kg=c.pe;e._emscripten_enum_OcrEngineMode_OEM_LSTM_ONLY=Lg=c.qe;e._emscripten_enum_OcrEngineMode_OEM_TESSERACT_LSTM_COMBINED=Mg=c.re;e._emscripten_enum_OcrEngineMode_OEM_DEFAULT=Ng=c.se;e._emscripten_enum_OcrEngineMode_OEM_COUNT=Og=c.te;e._emscripten_enum_WritingDirection__WRITING_DIRECTION_LEFT_TO_RIGHT=Pg=c.ue;e._emscripten_enum_WritingDirection__WRITING_DIRECTION_RIGHT_TO_LEFT=Qg=
c.ve;e._emscripten_enum_WritingDirection__WRITING_DIRECTION_TOP_TO_BOTTOM=Rg=c.we;e._emscripten_enum_PolyBlockType_PT_UNKNOWN=Sg=c.xe;e._emscripten_enum_PolyBlockType_PT_FLOWING_TEXT=Tg=c.ye;e._emscripten_enum_PolyBlockType_PT_HEADING_TEXT=Ug=c.ze;e._emscripten_enum_PolyBlockType_PT_PULLOUT_TEXT=Vg=c.Ae;e._emscripten_enum_PolyBlockType_PT_EQUATION=Wg=c.Be;e._emscripten_enum_PolyBlockType_PT_INLINE_EQUATION=Xg=c.Ce;e._emscripten_enum_PolyBlockType_PT_TABLE=Yg=c.De;e._emscripten_enum_PolyBlockType_PT_VERTICAL_TEXT=
Zg=c.Ee;e._emscripten_enum_PolyBlockType_PT_CAPTION_TEXT=$g=c.Fe;e._emscripten_enum_PolyBlockType_PT_FLOWING_IMAGE=ah=c.Ge;e._emscripten_enum_PolyBlockType_PT_HEADING_IMAGE=bh=c.He;e._emscripten_enum_PolyBlockType_PT_PULLOUT_IMAGE=ch=c.Ie;e._emscripten_enum_PolyBlockType_PT_HORZ_LINE=dh=c.Je;e._emscripten_enum_PolyBlockType_PT_VERT_LINE=eh=c.Ke;e._emscripten_enum_PolyBlockType_PT_NOISE=fh=c.Le;e._emscripten_enum_PolyBlockType_PT_COUNT=gh=c.Me;e._emscripten_enum_StrongScriptDirection_DIR_NEUTRAL=hh=
c.Ne;e._emscripten_enum_StrongScriptDirection_DIR_LEFT_TO_RIGHT=ih=c.Oe;e._emscripten_enum_StrongScriptDirection_DIR_RIGHT_TO_LEFT=jh=c.Pe;e._emscripten_enum_StrongScriptDirection_DIR_MIX=kh=c.Qe;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_UNKNOWN=lh=c.Re;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_LEFT=mh=c.Se;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_CENTER=nh=c.Te;e._emscripten_enum_ParagraphJustification__JUSTIFICATION_RIGHT=oh=c.Ue;e._emscripten_enum_TextlineOrder__TEXTLINE_ORDER_LEFT_TO_RIGHT=
ph=c.Ve;e._emscripten_enum_TextlineOrder__TEXTLINE_ORDER_RIGHT_TO_LEFT=qh=c.We;e._emscripten_enum_TextlineOrder__TEXTLINE_ORDER_TOP_TO_BOTTOM=rh=c.Xe;e._emscripten_enum_Orientation__ORIENTATION_PAGE_UP=sh=c.Ye;e._emscripten_enum_Orientation__ORIENTATION_PAGE_RIGHT=th=c.Ze;e._emscripten_enum_Orientation__ORIENTATION_PAGE_DOWN=uh=c._e;e._emscripten_enum_Orientation__ORIENTATION_PAGE_LEFT=vh=c.$e;e._emscripten_enum_PageSegMode_PSM_OSD_ONLY=wh=c.af;e._emscripten_enum_PageSegMode_PSM_AUTO_OSD=xh=c.bf;
e._emscripten_enum_PageSegMode_PSM_AUTO_ONLY=yh=c.cf;e._emscripten_enum_PageSegMode_PSM_AUTO=zh=c.df;e._emscripten_enum_PageSegMode_PSM_SINGLE_COLUMN=Ah=c.ef;e._emscripten_enum_PageSegMode_PSM_SINGLE_BLOCK_VERT_TEXT=Bh=c.ff;e._emscripten_enum_PageSegMode_PSM_SINGLE_BLOCK=Ch=c.gf;e._emscripten_enum_PageSegMode_PSM_SINGLE_LINE=Dh=c.hf;e._emscripten_enum_PageSegMode_PSM_SINGLE_WORD=Eh=c.jf;e._emscripten_enum_PageSegMode_PSM_CIRCLE_WORD=Fh=c.kf;e._emscripten_enum_PageSegMode_PSM_SINGLE_CHAR=Gh=c.lf;e._emscripten_enum_PageSegMode_PSM_SPARSE_TEXT=
Hh=c.mf;e._emscripten_enum_PageSegMode_PSM_SPARSE_TEXT_OSD=Ih=c.nf;e._emscripten_enum_PageSegMode_PSM_RAW_LINE=Jh=c.of;e._emscripten_enum_PageSegMode_PSM_COUNT=Kh=c.pf;e._pixDestroy=c.qf;e._ptaDestroy=c.rf;e._pixaDestroy=c.sf;e._boxaDestroy=c.tf;e._pixReadMem=c.uf;e._free=Lh=c.vf;e._malloc=Mh=c.wf;e._pixReadHeaderMem=c.xf;lb=c.yf;Nh=c.zf;Oh=c.Af;Ph=c.Bf;return ci}var b={a:ai};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});ya??=e.locateFile?e.locateFile?e.locateFile("tesseract-core.wasm",
ha):ha+"tesseract-core.wasm":(new URL("tesseract-core.wasm",import.meta.url)).href;return a((await Ba(b)).instance)}());bi();function D(){}D.prototype=Object.create(D.prototype);D.prototype.constructor=D;D.prototype.Hf=D;D.If={};e.WrapperObject=D;function di(a){return(a||D).If}e.getCache=di;function E(a,b){var c=di(b),d=c[a];if(d)return d;d=Object.create((b||D).prototype);d.Cf=a;return c[a]=d}e.wrapPointer=E;e.castObject=function(a,b){return E(a.Cf,b)};e.NULL=E(0);
e.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete di(a.Hf)[a.Cf]};e.compare=function(a,b){return a.Cf===b.Cf};e.getPointer=function(a){return a.Cf};e.getClass=function(a){return a.Hf};var ei=0,fi=0,gi=0,hi=[],ii=0;function F(){if(ii){for(var a=0;a<hi.length;a++)e._free(hi[a]);hi.length=0;e._free(ei);ei=0;fi+=ii;ii=0}ei||(fi+=128,(ei=e._malloc(fi))||r());gi=0}
function G(a){if("string"===typeof a){a=eb(a);var b=g;ei||r();b=a.length*b.BYTES_PER_ELEMENT;b=b+7&-8;if(gi+b>=fi){0<b||r();ii+=b;var c=e._malloc(b);hi.push(c)}else c=ei+gi,gi+=b;b=c;c=g;var d=b;switch(c.BYTES_PER_ELEMENT){case 2:d>>=1;break;case 4:d>>=2;break;case 8:d>>=3}for(var f=0;f<a.length;f++)c[d+f]=a[f];return b}return a}function ji(){throw"cannot construct a ParagraphJustification, no constructor in IDL";}ji.prototype=Object.create(D.prototype);ji.prototype.constructor=ji;
ji.prototype.Hf=ji;ji.If={};e.ParagraphJustification=ji;ji.prototype.__destroy__=function(){fc(this.Cf)};function ki(){throw"cannot construct a BoolPtr, no constructor in IDL";}ki.prototype=Object.create(D.prototype);ki.prototype.constructor=ki;ki.prototype.Hf=ki;ki.If={};e.BoolPtr=ki;ki.prototype.__destroy__=function(){gc(this.Cf)};function H(){throw"cannot construct a TessResultRenderer, no constructor in IDL";}H.prototype=Object.create(D.prototype);H.prototype.constructor=H;H.prototype.Hf=H;
H.If={};e.TessResultRenderer=H;H.prototype.BeginDocument=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);return!!hc(b,a)};H.prototype.AddImage=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!ic(b,a)};H.prototype.EndDocument=function(){return!!jc(this.Cf)};H.prototype.happy=function(){return!!kc(this.Cf)};H.prototype.file_extension=function(){return w(lc(this.Cf))};H.prototype.title=H.prototype.title=function(){return w(mc(this.Cf))};H.prototype.imagenum=function(){return nc(this.Cf)};
H.prototype.__destroy__=function(){oc(this.Cf)};function li(){throw"cannot construct a LongStarPtr, no constructor in IDL";}li.prototype=Object.create(D.prototype);li.prototype.constructor=li;li.prototype.Hf=li;li.If={};e.LongStarPtr=li;li.prototype.__destroy__=function(){pc(this.Cf)};function mi(){throw"cannot construct a VoidPtr, no constructor in IDL";}mi.prototype=Object.create(D.prototype);mi.prototype.constructor=mi;mi.prototype.Hf=mi;mi.If={};e.VoidPtr=mi;mi.prototype.__destroy__=function(){qc(this.Cf)};
function I(a){a&&"object"===typeof a&&(a=a.Cf);this.Cf=rc(a);di(I)[this.Cf]=this}I.prototype=Object.create(D.prototype);I.prototype.constructor=I;I.prototype.Hf=I;I.If={};e.ResultIterator=I;I.prototype.Begin=function(){sc(this.Cf)};I.prototype.RestartParagraph=function(){tc(this.Cf)};I.prototype.IsWithinFirstTextlineOfParagraph=function(){return!!uc(this.Cf)};I.prototype.RestartRow=function(){vc(this.Cf)};I.prototype.Next=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!wc(b,a)};
I.prototype.IsAtBeginningOf=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!xc(b,a)};I.prototype.IsAtFinalElement=function(a,b){var c=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);return!!yc(c,a,b)};I.prototype.Cmp=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return zc(b,a)};I.prototype.SetBoundingBoxComponents=function(a,b){var c=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);Ac(c,a,b)};
I.prototype.BoundingBox=function(a,b,c,d,f,h){var k=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);h&&"object"===typeof h&&(h=h.Cf);return void 0===h?!!Bc(k,a,b,c,d,f):!!Cc(k,a,b,c,d,f,h)};
I.prototype.BoundingBoxInternal=function(a,b,c,d,f){var h=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);return!!Dc(h,a,b,c,d,f)};I.prototype.Empty=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!Ec(b,a)};I.prototype.BlockType=function(){return Fc(this.Cf)};I.prototype.BlockPolygon=function(){return E(Gc(this.Cf),J)};
I.prototype.GetBinaryImage=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return E(Hc(b,a),L)};I.prototype.GetImage=function(a,b,c,d,f){var h=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);return E(Ic(h,a,b,c,d,f),L)};
I.prototype.Baseline=function(a,b,c,d,f){var h=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);return!!Jc(h,a,b,c,d,f)};I.prototype.RowAttributes=function(a,b,c){var d=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);return!!Kc(d,a,b,c)};
I.prototype.Orientation=function(a,b,c,d){var f=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);Lc(f,a,b,c,d)};I.prototype.ParagraphInfo=function(a,b,c,d){var f=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);Mc(f,a,b,c,d)};I.prototype.ParagraphIsLtr=function(){return!!Nc(this.Cf)};
I.prototype.GetUTF8Text=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return w(Oc(b,a))};I.prototype.SetLineSeparator=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);Pc(b,a)};I.prototype.SetParagraphSeparator=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);Qc(b,a)};I.prototype.Confidence=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return Rc(b,a)};
I.prototype.WordFontAttributes=function(a,b,c,d,f,h,k,m){var t=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);h&&"object"===typeof h&&(h=h.Cf);k&&"object"===typeof k&&(k=k.Cf);m&&"object"===typeof m&&(m=m.Cf);return w(Sc(t,a,b,c,d,f,h,k,m))};I.prototype.WordRecognitionLanguage=function(){return w(Tc(this.Cf))};I.prototype.WordDirection=function(){return Uc(this.Cf)};
I.prototype.WordIsFromDictionary=function(){return!!Vc(this.Cf)};I.prototype.WordIsNumeric=function(){return!!Wc(this.Cf)};I.prototype.HasBlamerInfo=function(){return!!Xc(this.Cf)};I.prototype.HasTruthString=function(){return!!Yc(this.Cf)};I.prototype.EquivalentToTruth=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);return!!Zc(b,a)};I.prototype.WordTruthUTF8Text=function(){return w($c(this.Cf))};I.prototype.WordNormedUTF8Text=function(){return w(ad(this.Cf))};
I.prototype.WordLattice=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return w(bd(b,a))};I.prototype.SymbolIsSuperscript=function(){return!!cd(this.Cf)};I.prototype.SymbolIsSubscript=function(){return!!dd(this.Cf)};I.prototype.SymbolIsDropcap=function(){return!!ed(this.Cf)};I.prototype.__destroy__=function(){fd(this.Cf)};function ni(){throw"cannot construct a TextlineOrder, no constructor in IDL";}ni.prototype=Object.create(D.prototype);ni.prototype.constructor=ni;ni.prototype.Hf=ni;
ni.If={};e.TextlineOrder=ni;ni.prototype.__destroy__=function(){gd(this.Cf)};function oi(){throw"cannot construct a ETEXT_DESC, no constructor in IDL";}oi.prototype=Object.create(D.prototype);oi.prototype.constructor=oi;oi.prototype.Hf=oi;oi.If={};e.ETEXT_DESC=oi;oi.prototype.__destroy__=function(){hd(this.Cf)};function M(){throw"cannot construct a PageIterator, no constructor in IDL";}M.prototype=Object.create(D.prototype);M.prototype.constructor=M;M.prototype.Hf=M;M.If={};e.PageIterator=M;
M.prototype.Begin=function(){jd(this.Cf)};M.prototype.RestartParagraph=function(){kd(this.Cf)};M.prototype.IsWithinFirstTextlineOfParagraph=function(){return!!ld(this.Cf)};M.prototype.RestartRow=function(){md(this.Cf)};M.prototype.Next=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!nd(b,a)};M.prototype.IsAtBeginningOf=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!od(b,a)};
M.prototype.IsAtFinalElement=function(a,b){var c=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);return!!pd(c,a,b)};M.prototype.Cmp=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return qd(b,a)};M.prototype.SetBoundingBoxComponents=function(a,b){var c=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);rd(c,a,b)};
M.prototype.BoundingBox=function(a,b,c,d,f,h){var k=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);h&&"object"===typeof h&&(h=h.Cf);return void 0===h?!!sd(k,a,b,c,d,f):!!td(k,a,b,c,d,f,h)};
M.prototype.BoundingBoxInternal=function(a,b,c,d,f){var h=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);return!!ud(h,a,b,c,d,f)};M.prototype.Empty=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!vd(b,a)};M.prototype.BlockType=function(){return wd(this.Cf)};M.prototype.BlockPolygon=function(){return E(xd(this.Cf),J)};
M.prototype.GetBinaryImage=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return E(yd(b,a),L)};M.prototype.GetImage=function(a,b,c,d,f){var h=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);return E(zd(h,a,b,c,d,f),L)};
M.prototype.Baseline=function(a,b,c,d,f){var h=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);return!!Ad(h,a,b,c,d,f)};M.prototype.Orientation=function(a,b,c,d){var f=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);Bd(f,a,b,c,d)};
M.prototype.ParagraphInfo=function(a,b,c,d){var f=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);Cd(f,a,b,c,d)};M.prototype.__destroy__=function(){Dd(this.Cf)};function qi(){throw"cannot construct a WritingDirection, no constructor in IDL";}qi.prototype=Object.create(D.prototype);qi.prototype.constructor=qi;qi.prototype.Hf=qi;qi.If={};e.WritingDirection=qi;qi.prototype.__destroy__=function(){Ed(this.Cf)};
function ri(a){a&&"object"===typeof a&&(a=a.Cf);this.Cf=Fd(a);di(ri)[this.Cf]=this}ri.prototype=Object.create(D.prototype);ri.prototype.constructor=ri;ri.prototype.Hf=ri;ri.If={};e.WordChoiceIterator=ri;ri.prototype.Next=function(){return!!Gd(this.Cf)};ri.prototype.GetUTF8Text=function(){return w(Hd(this.Cf))};ri.prototype.Confidence=function(){return Id(this.Cf)};ri.prototype.__destroy__=function(){Jd(this.Cf)};function N(){throw"cannot construct a Box, no constructor in IDL";}N.prototype=Object.create(D.prototype);
N.prototype.constructor=N;N.prototype.Hf=N;N.If={};e.Box=N;N.prototype.get_x=N.prototype.ng=function(){return Kd(this.Cf)};Object.defineProperty(N.prototype,"x",{get:N.prototype.ng});N.prototype.get_y=N.prototype.og=function(){return Ld(this.Cf)};Object.defineProperty(N.prototype,"y",{get:N.prototype.og});N.prototype.get_w=N.prototype.mg=function(){return Md(this.Cf)};Object.defineProperty(N.prototype,"w",{get:N.prototype.mg});N.prototype.get_h=N.prototype.lg=function(){return Nd(this.Cf)};
Object.defineProperty(N.prototype,"h",{get:N.prototype.lg});N.prototype.get_refcount=N.prototype.Uf=function(){return Od(this.Cf)};Object.defineProperty(N.prototype,"refcount",{get:N.prototype.Uf});N.prototype.__destroy__=function(){Pd(this.Cf)};function O(a,b,c){F();a=a&&"object"===typeof a?a.Cf:G(a);b=b&&"object"===typeof b?b.Cf:G(b);c&&"object"===typeof c&&(c=c.Cf);this.Cf=Qd(a,b,c);di(O)[this.Cf]=this}O.prototype=Object.create(D.prototype);O.prototype.constructor=O;O.prototype.Hf=O;O.If={};
e.TessPDFRenderer=O;O.prototype.BeginDocument=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);return!!Rd(b,a)};O.prototype.AddImage=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!Sd(b,a)};O.prototype.EndDocument=function(){return!!Td(this.Cf)};O.prototype.happy=function(){return!!Ud(this.Cf)};O.prototype.file_extension=function(){return w(Vd(this.Cf))};O.prototype.title=O.prototype.title=function(){return w(Wd(this.Cf))};O.prototype.imagenum=function(){return Xd(this.Cf)};
O.prototype.__destroy__=function(){Yd(this.Cf)};function si(){throw"cannot construct a PixaPtr, no constructor in IDL";}si.prototype=Object.create(D.prototype);si.prototype.constructor=si;si.prototype.Hf=si;si.If={};e.PixaPtr=si;si.prototype.__destroy__=function(){Zd(this.Cf)};function ti(){throw"cannot construct a FloatPtr, no constructor in IDL";}ti.prototype=Object.create(D.prototype);ti.prototype.constructor=ti;ti.prototype.Hf=ti;ti.If={};e.FloatPtr=ti;ti.prototype.__destroy__=function(){$d(this.Cf)};
function ui(a){a&&"object"===typeof a&&(a=a.Cf);this.Cf=ae(a);di(ui)[this.Cf]=this}ui.prototype=Object.create(D.prototype);ui.prototype.constructor=ui;ui.prototype.Hf=ui;ui.If={};e.ChoiceIterator=ui;ui.prototype.Next=function(){return!!be(this.Cf)};ui.prototype.GetUTF8Text=function(){return w(ce(this.Cf))};ui.prototype.Confidence=function(){return de(this.Cf)};ui.prototype.__destroy__=function(){ee(this.Cf)};function vi(){throw"cannot construct a PixPtr, no constructor in IDL";}vi.prototype=Object.create(D.prototype);
vi.prototype.constructor=vi;vi.prototype.Hf=vi;vi.If={};e.PixPtr=vi;vi.prototype.__destroy__=function(){fe(this.Cf)};function wi(){throw"cannot construct a UNICHARSET, no constructor in IDL";}wi.prototype=Object.create(D.prototype);wi.prototype.constructor=wi;wi.prototype.Hf=wi;wi.If={};e.UNICHARSET=wi;wi.prototype.get_script_from_script_id=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return w(ge(b,a))};
wi.prototype.get_script_id_from_name=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);return he(b,a)};wi.prototype.get_script_table_size=function(){return ie(this.Cf)};wi.prototype.__destroy__=function(){je(this.Cf)};function xi(){throw"cannot construct a IntPtr, no constructor in IDL";}xi.prototype=Object.create(D.prototype);xi.prototype.constructor=xi;xi.prototype.Hf=xi;xi.If={};e.IntPtr=xi;xi.prototype.__destroy__=function(){ke(this.Cf)};
function yi(){throw"cannot construct a Orientation, no constructor in IDL";}yi.prototype=Object.create(D.prototype);yi.prototype.constructor=yi;yi.prototype.Hf=yi;yi.If={};e.Orientation=yi;yi.prototype.__destroy__=function(){le(this.Cf)};function P(){throw"cannot construct a OSBestResult, no constructor in IDL";}P.prototype=Object.create(D.prototype);P.prototype.constructor=P;P.prototype.Hf=P;P.If={};e.OSBestResult=P;P.prototype.get_orientation_id=P.prototype.dh=function(){return me(this.Cf)};
Object.defineProperty(P.prototype,"orientation_id",{get:P.prototype.dh});P.prototype.get_script_id=P.prototype.gh=function(){return ne(this.Cf)};Object.defineProperty(P.prototype,"script_id",{get:P.prototype.gh});P.prototype.get_sconfidence=P.prototype.fh=function(){return oe(this.Cf)};Object.defineProperty(P.prototype,"sconfidence",{get:P.prototype.fh});P.prototype.get_oconfidence=P.prototype.bh=function(){return pe(this.Cf)};Object.defineProperty(P.prototype,"oconfidence",{get:P.prototype.bh});
P.prototype.__destroy__=function(){qe(this.Cf)};function Q(){throw"cannot construct a Boxa, no constructor in IDL";}Q.prototype=Object.create(D.prototype);Q.prototype.constructor=Q;Q.prototype.Hf=Q;Q.If={};e.Boxa=Q;Q.prototype.get_n=Q.prototype.Yf=function(){return re(this.Cf)};Object.defineProperty(Q.prototype,"n",{get:Q.prototype.Yf});Q.prototype.get_nalloc=Q.prototype.Zf=function(){return se(this.Cf)};Object.defineProperty(Q.prototype,"nalloc",{get:Q.prototype.Zf});
Q.prototype.get_refcount=Q.prototype.Uf=function(){return te(this.Cf)};Object.defineProperty(Q.prototype,"refcount",{get:Q.prototype.Uf});Q.prototype.get_box=Q.prototype.Vg=function(){return E(ue(this.Cf),zi)};Object.defineProperty(Q.prototype,"box",{get:Q.prototype.Vg});Q.prototype.__destroy__=function(){ve(this.Cf)};function R(){throw"cannot construct a PixColormap, no constructor in IDL";}R.prototype=Object.create(D.prototype);R.prototype.constructor=R;R.prototype.Hf=R;R.If={};e.PixColormap=R;
R.prototype.get_array=R.prototype.Tg=function(){return we(this.Cf)};Object.defineProperty(R.prototype,"array",{get:R.prototype.Tg});R.prototype.get_depth=R.prototype.$g=function(){return xe(this.Cf)};Object.defineProperty(R.prototype,"depth",{get:R.prototype.$g});R.prototype.get_nalloc=R.prototype.Zf=function(){return ye(this.Cf)};Object.defineProperty(R.prototype,"nalloc",{get:R.prototype.Zf});R.prototype.get_n=R.prototype.Yf=function(){return ze(this.Cf)};Object.defineProperty(R.prototype,"n",{get:R.prototype.Yf});
R.prototype.__destroy__=function(){Ae(this.Cf)};function J(){throw"cannot construct a Pta, no constructor in IDL";}J.prototype=Object.create(D.prototype);J.prototype.constructor=J;J.prototype.Hf=J;J.If={};e.Pta=J;J.prototype.get_n=J.prototype.Yf=function(){return Be(this.Cf)};Object.defineProperty(J.prototype,"n",{get:J.prototype.Yf});J.prototype.get_nalloc=J.prototype.Zf=function(){return Ce(this.Cf)};Object.defineProperty(J.prototype,"nalloc",{get:J.prototype.Zf});
J.prototype.get_refcount=J.prototype.Uf=function(){return De(this.Cf)};Object.defineProperty(J.prototype,"refcount",{get:J.prototype.Uf});J.prototype.get_x=J.prototype.ng=function(){return E(Ee(this.Cf),ti)};Object.defineProperty(J.prototype,"x",{get:J.prototype.ng});J.prototype.get_y=J.prototype.og=function(){return E(Fe(this.Cf),ti)};Object.defineProperty(J.prototype,"y",{get:J.prototype.og});J.prototype.__destroy__=function(){Ge(this.Cf)};
function L(){throw"cannot construct a Pix, no constructor in IDL";}L.prototype=Object.create(D.prototype);L.prototype.constructor=L;L.prototype.Hf=L;L.If={};e.Pix=L;L.prototype.get_w=L.prototype.mg=function(){return He(this.Cf)};Object.defineProperty(L.prototype,"w",{get:L.prototype.mg});L.prototype.get_h=L.prototype.lg=function(){return Ie(this.Cf)};Object.defineProperty(L.prototype,"h",{get:L.prototype.lg});L.prototype.get_d=L.prototype.Yg=function(){return Je(this.Cf)};
Object.defineProperty(L.prototype,"d",{get:L.prototype.Yg});L.prototype.get_spp=L.prototype.ih=function(){return Ke(this.Cf)};Object.defineProperty(L.prototype,"spp",{get:L.prototype.ih});L.prototype.get_wpl=L.prototype.lh=function(){return Le(this.Cf)};Object.defineProperty(L.prototype,"wpl",{get:L.prototype.lh});L.prototype.get_refcount=L.prototype.Uf=function(){return Me(this.Cf)};Object.defineProperty(L.prototype,"refcount",{get:L.prototype.Uf});L.prototype.get_xres=L.prototype.mh=function(){return Ne(this.Cf)};
Object.defineProperty(L.prototype,"xres",{get:L.prototype.mh});L.prototype.get_yres=L.prototype.nh=function(){return Oe(this.Cf)};Object.defineProperty(L.prototype,"yres",{get:L.prototype.nh});L.prototype.get_informat=L.prototype.ah=function(){return Pe(this.Cf)};Object.defineProperty(L.prototype,"informat",{get:L.prototype.ah});L.prototype.get_special=L.prototype.hh=function(){return Qe(this.Cf)};Object.defineProperty(L.prototype,"special",{get:L.prototype.hh});
L.prototype.get_text=L.prototype.jh=function(){return w(Re(this.Cf))};Object.defineProperty(L.prototype,"text",{get:L.prototype.jh});L.prototype.get_colormap=L.prototype.Xg=function(){return E(Se(this.Cf),R)};Object.defineProperty(L.prototype,"colormap",{get:L.prototype.Xg});L.prototype.get_data=L.prototype.Zg=function(){return Te(this.Cf)};Object.defineProperty(L.prototype,"data",{get:L.prototype.Zg});L.prototype.__destroy__=function(){Ue(this.Cf)};
function Ai(){throw"cannot construct a DoublePtr, no constructor in IDL";}Ai.prototype=Object.create(D.prototype);Ai.prototype.constructor=Ai;Ai.prototype.Hf=Ai;Ai.If={};e.DoublePtr=Ai;Ai.prototype.__destroy__=function(){Ve(this.Cf)};function Bi(){throw"cannot construct a Dawg, no constructor in IDL";}Bi.prototype=Object.create(D.prototype);Bi.prototype.constructor=Bi;Bi.prototype.Hf=Bi;Bi.If={};e.Dawg=Bi;Bi.prototype.__destroy__=function(){We(this.Cf)};
function zi(){throw"cannot construct a BoxPtr, no constructor in IDL";}zi.prototype=Object.create(D.prototype);zi.prototype.constructor=zi;zi.prototype.Hf=zi;zi.If={};e.BoxPtr=zi;zi.prototype.__destroy__=function(){Xe(this.Cf)};function S(){this.Cf=Ye();di(S)[this.Cf]=this}S.prototype=Object.create(D.prototype);S.prototype.constructor=S;S.prototype.Hf=S;S.If={};e.TessBaseAPI=S;S.prototype.Version=function(){return w(Ze(this.Cf))};
S.prototype.SetInputName=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);$e(b,a)};S.prototype.GetInputName=function(){return w(af(this.Cf))};S.prototype.SetInputImage=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);bf(b,a)};S.prototype.GetInputImage=function(){return E(cf(this.Cf),L)};S.prototype.GetSourceYResolution=function(){return df(this.Cf)};S.prototype.GetDatapath=function(){return w(ef(this.Cf))};
S.prototype.SetOutputName=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);ff(b,a)};S.prototype.SetVariable=S.prototype.SetVariable=function(a,b){var c=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);b=b&&"object"===typeof b?b.Cf:G(b);return!!gf(c,a,b)};S.prototype.SetDebugVariable=function(a,b){var c=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);b=b&&"object"===typeof b?b.Cf:G(b);return!!hf(c,a,b)};
S.prototype.GetIntVariable=function(a,b){var c=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);b&&"object"===typeof b&&(b=b.Cf);return!!jf(c,a,b)};S.prototype.GetBoolVariable=function(a,b){var c=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);b&&"object"===typeof b&&(b=b.Cf);return!!kf(c,a,b)};S.prototype.GetDoubleVariable=function(a,b){var c=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);b&&"object"===typeof b&&(b=b.Cf);return!!lf(c,a,b)};
S.prototype.GetStringVariable=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);return w(mf(b,a))};S.prototype.Init=function(a,b,c,d){void 0===c&&void 0!==d&&(c=3);var f=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);b=b&&"object"===typeof b?b.Cf:G(b);d=d&&"object"===typeof d?d.Cf:G(d);c&&"object"===typeof c&&(c=c.Cf);return void 0===c&&void 0!==d?rf(f,a,b,3,d):void 0===c?pf(f,a,b):void 0===d?qf(f,a,b,c):rf(f,a,b,c,d)};S.prototype.GetInitLanguagesAsString=function(){return w(sf(this.Cf))};
S.prototype.InitForAnalysePage=function(){tf(this.Cf)};S.prototype.SaveParameters=function(){nf(this.Cf)};S.prototype.RestoreParameters=function(){of(this.Cf)};S.prototype.ReadConfigFile=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);uf(b,a)};S.prototype.ReadDebugConfigFile=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);vf(b,a)};S.prototype.SetPageSegMode=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);wf(b,a)};S.prototype.GetPageSegMode=function(){return xf(this.Cf)};
S.prototype.TesseractRect=function(a,b,c,d,f,h,k){var m=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);h&&"object"===typeof h&&(h=h.Cf);k&&"object"===typeof k&&(k=k.Cf);return w(yf(m,a,b,c,d,f,h,k))};S.prototype.ClearAdaptiveClassifier=function(){zf(this.Cf)};S.prototype.PopulateLearningReferenceFromCurrentResult=function(){Af(this.Cf)};
S.prototype.ClearLearningReferenceWords=function(){Bf(this.Cf)};S.prototype.SetImage=function(a,b,c,d,f,h=1,k=0,m=!1){var t=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);void 0===b||null===b?Cf(t,a,h,k,m):Df(t,a,b,c,d,f,h,k,m)};S.prototype.SetImageFile=function(a=1,b=0,c=!1){return Ef(this.Cf,a,b,c)};
S.prototype.SetSourceResolution=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);Ff(b,a)};S.prototype.SetRectangle=function(a,b,c,d){var f=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);Gf(f,a,b,c,d)};S.prototype.GetThresholdedImage=function(){return E(Hf(this.Cf),L)};S.prototype.WriteImage=function(a){If(this.Cf,a)};
S.prototype.GetRegions=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return E(Mf(b,a),Q)};
S.prototype.GetTextlines=function(a,b,c,d,f){var h=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);return void 0===c?E(Nf(h,a,b),Q):void 0===d?E(_emscripten_bind_TessBaseAPI_GetTextlines_3(h,a,b,c),Q):void 0===f?E(_emscripten_bind_TessBaseAPI_GetTextlines_4(h,a,b,c,d),Q):E(Of(h,a,b,c,d,f),Q)};
S.prototype.GetStrips=function(a,b){var c=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);return E(Pf(c,a,b),Q)};S.prototype.GetWords=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return E(Qf(b,a),Q)};S.prototype.GetConnectedComponents=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return E(Rf(b,a),Q)};
S.prototype.GetComponentImages=function(a,b,c,d,f,h,k){var m=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);f&&"object"===typeof f&&(f=f.Cf);h&&"object"===typeof h&&(h=h.Cf);k&&"object"===typeof k&&(k=k.Cf);return void 0===f?E(Sf(m,a,b,c,d),Q):void 0===h?E(_emscripten_bind_TessBaseAPI_GetComponentImages_5(m,a,b,c,d,f),Q):void 0===k?E(_emscripten_bind_TessBaseAPI_GetComponentImages_6(m,a,b,c,d,f,h),Q):E(Tf(m,
a,b,c,d,f,h,k),Q)};S.prototype.GetThresholdedImageScaleFactor=function(){return Uf(this.Cf)};S.prototype.AnalyseLayout=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return void 0===a?E(Vf(b),M):E(Wf(b,a),M)};S.prototype.Recognize=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return Xf(b,a)};S.prototype.FindLines=function(){return Jf(this.Cf)};S.prototype.GetGradient=function(){return Kf(this.Cf)};S.prototype.GetEstimatedResolution=function(){return Lf(this.Cf)};
S.prototype.ProcessPages=function(a,b,c,d){var f=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);b=b&&"object"===typeof b?b.Cf:G(b);c&&"object"===typeof c&&(c=c.Cf);d&&"object"===typeof d&&(d=d.Cf);return!!Yf(f,a,b,c,d)};
S.prototype.ProcessPage=function(a,b,c,d,f,h){var k=this.Cf;F();a&&"object"===typeof a&&(a=a.Cf);b&&"object"===typeof b&&(b=b.Cf);c=c&&"object"===typeof c?c.Cf:G(c);d=d&&"object"===typeof d?d.Cf:G(d);f&&"object"===typeof f&&(f=f.Cf);h&&"object"===typeof h&&(h=h.Cf);return!!Zf(k,a,b,c,d,f,h)};S.prototype.GetIterator=function(){return E($f(this.Cf),I)};S.prototype.GetUTF8Text=function(){var a=ag(this.Cf),b=a?v(l,a):"";Lh(a);return b};
S.prototype.GetHOCRText=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b=(a=bg(b,a))?v(l,a):"";Lh(a);return b};S.prototype.GetTSVText=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b=(a=dg(b,a))?v(l,a):"";Lh(a);return b};S.prototype.GetJSONText=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b=(a=cg(b,a))?v(l,a):"";Lh(a);return b};S.prototype.GetBoxText=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b=(a=eg(b,a))?v(l,a):"";Lh(a);return b};
S.prototype.GetUNLVText=function(){var a=fg(this.Cf),b=a?v(l,a):"";Lh(a);return b};S.prototype.GetOsdText=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);b=(a=gg(b,a))?v(l,a):"";Lh(a);return b};S.prototype.MeanTextConf=function(){return hg(this.Cf)};S.prototype.AllWordConfidences=function(){return E(ig(this.Cf),xi)};
S.prototype.AdaptToWordStr=function(a,b){var c=this.Cf;F();a&&"object"===typeof a&&(a=a.Cf);b=b&&"object"===typeof b?b.Cf:G(b);return!!_emscripten_bind_TessBaseAPI_AdaptToWordStr_2(c,a,b)};S.prototype.Clear=function(){jg(this.Cf)};S.prototype.End=function(){kg(this.Cf)};S.prototype.ClearPersistentCache=function(){lg(this.Cf)};S.prototype.IsValidWord=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);return mg(b,a)};
S.prototype.IsValidCharacter=function(a){var b=this.Cf;F();a=a&&"object"===typeof a?a.Cf:G(a);return!!ng(b,a)};S.prototype.DetectOS=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return!!og(b,a)};S.prototype.GetUnichar=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return w(pg(b,a))};S.prototype.GetDawg=function(a){var b=this.Cf;a&&"object"===typeof a&&(a=a.Cf);return E(qg(b,a),Bi)};S.prototype.NumDawgs=function(){return rg(this.Cf)};S.prototype.oem=function(){return sg(this.Cf)};
S.prototype.__destroy__=function(){tg(this.Cf)};function T(){this.Cf=ug();di(T)[this.Cf]=this}T.prototype=Object.create(D.prototype);T.prototype.constructor=T;T.prototype.Hf=T;T.If={};e.OSResults=T;T.prototype.print_scores=function(){vg(this.Cf)};T.prototype.get_best_result=T.prototype.Ug=function(){return E(wg(this.Cf),P)};Object.defineProperty(T.prototype,"best_result",{get:T.prototype.Ug});T.prototype.get_unicharset=T.prototype.kh=function(){return E(xg(this.Cf),wi)};
Object.defineProperty(T.prototype,"unicharset",{get:T.prototype.kh});T.prototype.__destroy__=function(){yg(this.Cf)};function V(){throw"cannot construct a Pixa, no constructor in IDL";}V.prototype=Object.create(D.prototype);V.prototype.constructor=V;V.prototype.Hf=V;V.If={};e.Pixa=V;V.prototype.get_n=V.prototype.Yf=function(){return zg(this.Cf)};Object.defineProperty(V.prototype,"n",{get:V.prototype.Yf});V.prototype.get_nalloc=V.prototype.Zf=function(){return Ag(this.Cf)};
Object.defineProperty(V.prototype,"nalloc",{get:V.prototype.Zf});V.prototype.get_refcount=V.prototype.Uf=function(){return Bg(this.Cf)};Object.defineProperty(V.prototype,"refcount",{get:V.prototype.Uf});V.prototype.get_pix=V.prototype.eh=function(){return E(Cg(this.Cf),vi)};Object.defineProperty(V.prototype,"pix",{get:V.prototype.eh});V.prototype.get_boxa=V.prototype.Wg=function(){return E(Dg(this.Cf),Q)};Object.defineProperty(V.prototype,"boxa",{get:V.prototype.Wg});V.prototype.__destroy__=function(){Eg(this.Cf)};
(function(){function a(){e.RIL_BLOCK=Fg();e.RIL_PARA=Gg();e.RIL_TEXTLINE=Hg();e.RIL_WORD=Ig();e.RIL_SYMBOL=Jg();e.OEM_TESSERACT_ONLY=Kg();e.OEM_LSTM_ONLY=Lg();e.OEM_TESSERACT_LSTM_COMBINED=Mg();e.OEM_DEFAULT=Ng();e.OEM_COUNT=Og();e.WRITING_DIRECTION_LEFT_TO_RIGHT=Pg();e.WRITING_DIRECTION_RIGHT_TO_LEFT=Qg();e.WRITING_DIRECTION_TOP_TO_BOTTOM=Rg();e.PT_UNKNOWN=Sg();e.PT_FLOWING_TEXT=Tg();e.PT_HEADING_TEXT=Ug();e.PT_PULLOUT_TEXT=Vg();e.PT_EQUATION=Wg();e.PT_INLINE_EQUATION=Xg();e.PT_TABLE=Yg();e.PT_VERTICAL_TEXT=
Zg();e.PT_CAPTION_TEXT=$g();e.PT_FLOWING_IMAGE=ah();e.PT_HEADING_IMAGE=bh();e.PT_PULLOUT_IMAGE=ch();e.PT_HORZ_LINE=dh();e.PT_VERT_LINE=eh();e.PT_NOISE=fh();e.PT_COUNT=gh();e.DIR_NEUTRAL=hh();e.DIR_LEFT_TO_RIGHT=ih();e.DIR_RIGHT_TO_LEFT=jh();e.DIR_MIX=kh();e.JUSTIFICATION_UNKNOWN=lh();e.JUSTIFICATION_LEFT=mh();e.JUSTIFICATION_CENTER=nh();e.JUSTIFICATION_RIGHT=oh();e.TEXTLINE_ORDER_LEFT_TO_RIGHT=ph();e.TEXTLINE_ORDER_RIGHT_TO_LEFT=qh();e.TEXTLINE_ORDER_TOP_TO_BOTTOM=rh();e.ORIENTATION_PAGE_UP=sh();
e.ORIENTATION_PAGE_RIGHT=th();e.ORIENTATION_PAGE_DOWN=uh();e.ORIENTATION_PAGE_LEFT=vh();e.PSM_OSD_ONLY=wh();e.PSM_AUTO_OSD=xh();e.PSM_AUTO_ONLY=yh();e.PSM_AUTO=zh();e.PSM_SINGLE_COLUMN=Ah();e.PSM_SINGLE_BLOCK_VERT_TEXT=Bh();e.PSM_SINGLE_BLOCK=Ch();e.PSM_SINGLE_LINE=Dh();e.PSM_SINGLE_WORD=Eh();e.PSM_CIRCLE_WORD=Fh();e.PSM_SINGLE_CHAR=Gh();e.PSM_SPARSE_TEXT=Hh();e.PSM_SPARSE_TEXT_OSD=Ih();e.PSM_RAW_LINE=Jh();e.PSM_COUNT=Kh()}if(e.runtimeInitialized)a();else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=
b?function(){b.call(this);a()}:function(){a()}}})();ki.prototype.getValue=function(a){return!!Ha(this.Cf+(a||0),"i8")};xi.prototype.getValue=function(a){return Ha(this.Cf+4*(a||0),"i32")};ti.prototype.getValue=function(a){return Ha(this.Cf+4*(a||0),"float")};Ai.prototype.getValue=function(a){return Ha(this.Cf+8*(a||0),"double")};zi.prototype.get=si.prototype.get=vi.prototype.get=function(a){return Ha(this.Cf+4*(a||0),"*")};function Ci(){this.cg={}}
Ci.prototype.wrap=function(a,b){var c=Mh(4);Ja(c,0,"i32");return this.cg[a]=E(c,b)};Ci.prototype.bool=function(a){return this.wrap(a,ki)};Ci.prototype.i32=function(a){return this.wrap(a,xi)};Ci.prototype.f32=function(a){return this.wrap(a,ti)};Ci.prototype.f64=function(a){return this.cg[a]=E(Mh(8),Ai)};Ci.prototype.peek=function(){var a={},b;for(b in this.cg)a[b]=this.cg[b].getValue();return a};Ci.prototype.get=function(){var a={},b;for(b in this.cg)a[b]=this.cg[b].getValue(),Lh(this.cg[b].Cf);return a};
I.prototype.getBoundingBox=function(a){var b=new Ci;this.BoundingBox(a,b.i32("x0"),b.i32("y0"),b.i32("x1"),b.i32("y1"));return b.get()};I.prototype.getBaseline=function(a){var b=new Ci;a=!!this.Baseline(a,b.i32("x0"),b.i32("y0"),b.i32("x1"),b.i32("y1"));b=b.get();b.has_baseline=a;return b};I.prototype.getRowAttributes=function(){var a=new Ci;this.RowAttributes(a.f32("row_height"),a.f32("descenders"),a.f32("ascenders"));return a.get()};
I.prototype.getWordFontAttributes=function(){var a=new Ci,b=this.WordFontAttributes(a.bool("is_bold"),a.bool("is_italic"),a.bool("is_underlined"),a.bool("is_monospace"),a.bool("is_serif"),a.bool("is_smallcaps"),a.i32("pointsize"),a.i32("font_id"));a=a.get();a.font_name=b;return a};e.pointerHelper=Ci;wa?moduleRtn=e:moduleRtn=new Promise((a,b)=>{pa=a;qa=b});
;return moduleRtn}export default TesseractCore;
